import { VAULT_NOT_DEPLOYED } from "@agari/core/vault";

/** Session-key tap-trading, the sponsor rail and the Ticket's funding source. */
export const SESSION = {
  notDeployed: VAULT_NOT_DEPLOYED,
  chip: {
    on: "tap-trading on",
    off: "tap-trading",
    needsKey: "tap-trading · needs a key",
    expired: "tap-trading · expired",
    titleOn: "Taps sign from a session key inside the caps you set. Open to see them.",
    titleOff: "Arm popup-free taps inside caps you set, funded from your Trading Balance.",
    titleNeedsKey: "A session grant is live but this browser holds no key for it. Open to revoke or re-key.",
    titleExpired: "The session grant expired. Open to arm a new one.",
    titleNoWallet: "Connect a wallet to arm tap-trading.",
  },
  route: {
    label: "Pay from",
    wallet: "Wallet",
    vault: "Trading Balance",
    vaultEmpty: "Your Trading Balance is empty — deposit on Portfolio first.",
    armedLocked: "Tap-trading is on: taps come from your Vault.",
    fromVault: "betting from your Vault",
    fromWallet: "betting from your wallet",
    fromGrant: (headroomText: string) => `betting from your Vault · ${headroomText} left today`,
    vaultNote: (availableText: string) => `Escrow comes from your Trading Balance (${availableText}); the fill is what the vault books.`,
    fallback: (reason: string) => `Tap-trading can't cover this one — ${reason}. Signing from your wallet instead.`,
  },
  sheet: {
    title: "Arm tap-trading",
    intro: "Deposit into your Trading Balance and hand a browser key the right to tap inside these caps. The key can never withdraw; only your wallet can.",
    perTrade: "Per tap",
    daily: "Per day",
    positions: "Open Windows",
    price: "Dearest odds",
    priceHint: "Never pays more than this per contract, in the side's own terms.",
    expiry: "Expires in",
    deposit: "Deposit now",
    depositHint: "Moves into your Trading Balance and becomes the key's budget.",
    budgetEqualsDeposit: "The grant's budget is this deposit.",
    example: (perTap: string, taps: number, daily: string, budget: string) =>
      `At ${perTap} a tap the key can place ${taps} ${taps === 1 ? "tap" : "taps"} today before the ${daily} daily cap stops it; the ${budget} budget covers exactly that.`,
    exampleShortBudget: (perTap: string, taps: number, budget: string) => `At ${perTap} a tap the ${budget} budget runs out after ${taps} ${taps === 1 ? "tap" : "taps"} — the daily cap never binds.`,
    resets: "Daily caps reset at 00:00 UTC.",
    receiptTitle: "What you are signing",
    receipt: {
      scope: "Scope",
      scopeValue: "Buy Up or Down on any live Window, from your Trading Balance",
      cannot: "Never",
      cannotValue: "withdraw, change where money goes, or spend past the caps",
      key: "Key",
      expiresAt: "Expires",
      gas: "Fees",
      gasSponsor: "paid by the sponsor; the key holds no SOL",
      gasKey: (amountText: string) => `paid by the key — ${amountText} SOL moves to it now`,
      signatures: "Signatures",
      sigsOne: "one: the deposit and grant, together",
      sigsWithTopUp: "one: the deposit, the grant and the key's SOL, together",
    },
    cta: "Arm tap-trading",
    ctaBusy: "Arming…",
    armed: "Tap-trading is on.",
    armedBody: "Taps on this browser sign from the session key inside your caps.",
    errors: {
      perTrade: "Per-tap cap must be at least the minimum stake.",
      daily: "Daily cap must be at least the per-tap cap.",
      deposit: "Deposit at least the per-tap cap.",
      price: "Dearest odds must be between 1¢ and 99¢.",
      positions: "Allow at least one open Window.",
      walletShort: (haveText: string) => `Your wallet holds ${haveText}; lower the deposit or use the faucet.`,
    },
  },
  /** The modal's first face — the reference's AccountSetup sentence (L68–72), with our facts in the second half. */
  modal: {
    eyebrow: "Tap-trading · session key",
    close: "Close",
    lead: "Arm tap-trading once, tap in one signature forever.",
    sponsored: "Fees are on us: free, takes a few seconds.",
    keyPays: "Takes a few seconds and a little SOL for the key's fees.",
    skip: "Skip it, and every tap simply asks your wallet instead.",
    adjust: (perTap: string, daily: string, expiry: string) => `Adjust the caps — ${perTap} a tap · ${daily} a day · ${expiry}`,
  },
  manager: {
    title: "Tap-trading",
    description: "Review what this key can do and how much it can spend.",
    key: "Key",
    scope: "Scope",
    caps: "Limits",
    perTap: "Per tap",
    perDay: "Per day",
    positions: "Max open Windows",
    price: "Max contract price",
    noPriceCap: "No cap",
    usage: "Usage",
    details: "Key details",
    spentToday: "Spent today",
    headroom: "Left today",
    budget: "Budget left",
    expires: "Expires",
    resets: "Resets at",
    gas: "Fees",
    gasSponsor: (sponsorText: string) => `Sponsored by ${sponsorText}`,
    gasSponsorDeclined: (reason: string) => `The sponsor declined the last tap (${reason}); the key paid.`,
    gasKey: (balanceText: string, taps: number) => `The key pays. It holds ${balanceText} SOL, enough for ${taps} ${taps === 1 ? "tap" : "taps"} at the base fee.`,
    gasKeyEmpty: "The key pays but holds no SOL. Top it up, or taps will fall back to your wallet.",
    topUp: (amountText: string) => `Move ${amountText} SOL to the key`,
    revoke: "Revoke",
    revoking: "Revoking…",
    revokeNote: "One signature. The unspent budget returns to your Trading Balance; positions the key opened stay yours.",
    needsKeyTitle: "A grant with no key",
    needsKeyBody: "The vault holds a live session grant for a key this browser does not have — cleared storage, or another browser. Revoke it, or re-key: a new grant to a fresh key with the same caps and budget.",
    rekey: "Re-key",
    rekeying: "Re-keying…",
    expiredTitle: "The grant expired",
    expiredBody: "Nothing can tap from it any more. Arm a new one when you want popup-free taps again.",
    forget: "Forget this key",
    forgetNote: "Deletes the key from this browser. Do it after revoking — a live grant with no key just sits there.",
    armNew: "Arm tap-trading",
  },
  recovery: {
    title: "Session key",
  },
  dev: {
    title: "Session key",
    intro: "Every state of the chip, the route control, the enable sheet and the manager, from canned views. Nothing here signs.",
    states: "Chip and manager",
    route: "Pay-from control",
    sheet: "Enable sheet",
    live: "Live — the connected wallet",
  },
} as const;
