/** `/who-sees-what` (C-ADD-11): the page's own sentences around the matrix in `matrix.ts`. */
export const WHO_SEES_WHAT = {
  title: "Who Sees What",
  meta: "Every contract in Owarine's Daml packages and the parties whose nodes receive it, the limits said plainly, and the commands that prove it.",
  lead: "On Canton a party receives a contract only if it is a stakeholder: a signatory or an observer. Nothing below is a screen filter. Each row is read from the contract's own signatory and observer lines, and the rows marked T are asserted by a Daml Script test.",
  back: "Back to How It Works",
  legendTitle: "Reading the table",
  legend: [
    ["✓", "a stakeholder: its node receives the contract"],
    ["—", "never receives it"],
    ["W", "sees it only as a witness of its own settle, or disclosed to it for one command"],
    ["own", "receives only the ones it signed itself"],
    ["T", "asserted by a test in Test.Privacy"],
  ] as const,
  cell: { yes: "✓", no: "—", witness: "W", own: "own" } as const,
  cellLabel: { yes: "receives it", no: "never receives it", witness: "sees it only as a witness", own: "receives only its own" } as const,
  contract: "Contract",
  signatory: "Signed by",
  observer: "Observed by",
  tested: "Asserted by a Daml Script test",
  scroll: (title: string) => `${title}: who receives each contract`,
  others: "Agents, tickets and games",
  notHidden: "What this does not hide",
  notHiddenLead: "Said before anyone has to ask. The privacy is between parties; it is not privacy from the venue, from the node operator or from the synchronizer's metadata.",
  run: "Run it yourself",
  runLead: "Three ways to check the table, from the Daml alone to a live request.",
  look: "Look for",
  trust: "The trust boundary of this demo, in one panel, sits on every proof page.",
  trustLink: "Open the proof page →",
} as const;
