/**
 * `@agari/markets/desk`: the agent desk. The reference's mainnet desk (Jupiter on Solana) becomes a Canton
 * `DeskMandate` whose live leg is gated on C7b; practice desks stay paper ledgers and never call this module. C1
 * stub: shapes and reference constants are kept, every read and write refuses as not live.
 */
export {
  DESK_MINTS,
  deskSymbolOfMint,
  JUPITER_V6,
  TOKEN_2022_PROGRAM,
  TOKEN_PROGRAM,
  tokenProgramOf,
  USDC_MAINNET,
  type DeskAllowedToken,
  type DeskEvent,
  type DeskEventName,
  type DeskHistoryEntry,
  type DeskInitPlan,
  type DeskInitRecord,
  type DeskInitWant,
  type DeskMainnetSession,
  type DeskMainnetSessionConfig,
  type DeskMintState,
  type DeskRefState,
  type DeskRpc,
  type DeskState,
  type DeskTokenAccountState,
  type DeskWriteResult,
  type DiscoveredDesk,
  type Landing,
  type OwnerDeskBalances,
  type OwnerNameBalance,
  type SealedAction,
  type SignatureOutcome,
} from "./types";
export {
  associatedTokenAddress,
  chainNowSec,
  createBrowserDeskRpc,
  createDeskMainnetSession,
  createDeskRpc,
  deskAddress,
  deskTokenAccounts,
  initDesk,
  listDesksByOperator,
  readDeskEventsOf,
  readDeskHistory,
  readDeskInitPlan,
  readDeskMints,
  readDeskState,
  readOwnerDeskBalances,
  readSealsOf,
  sealedActionsOf,
  signatureOutcome,
  swapAccountsOf,
  type Instruction,
} from "./ops";
export {
  buy,
  buyIx,
  checkpoint,
  createDeskOperatorClient,
  DeskSendError,
  DeskSendUnknownError,
  forkAirdrop,
  forkSetTokenAccount,
  forkTimeTravel,
  NotRefusedError,
  pauseIx,
  postReference,
  postReferenceInstructions,
  prewarmRoute,
  quoteSwap,
  refreshRoute,
  sell,
  sendForRefusal,
  swapInstructions,
  tokenBalance,
  withdrawAsStrangerIx,
  type CheckpointAction,
  type DeskOperatorClient,
  type DeskOperatorClientConfig,
  type DeskSendOptions,
  type DeskSendResult,
  type JupiterQuote,
  type JupiterRoute,
  type PostReferenceAction,
  type PostReferenceInput,
  type Prewarmed,
  type QuoteInput,
  type Refusal,
  type RefusalOptions,
  type RefusalStage,
  type SwapAction,
  type SwapInstructionsInput,
  type SwapResult,
} from "./operator";
