/** The verdict and claim words — split from `copy.ts` for the 400-line rule; imported through `@/lib/copy` as before. */

export const VERDICT_UI = {
  title: "Verdict",
  netPnl: "Net P&L",
  paidOut: "Paid out",
  costUnknown: "No entry cost on record for this wallet — showing the payout.",
  legs: "Your legs",
  contracts: "contracts",
  payout: "payout",
  receiptTitle: "Settlement receipt",
  window: "Window",
  openingPrint: "Opening print",
  closingPrint: "Closing print",
  settlementTx: "Settlement tx",
  pendingTx: "landing on chain…",
  oracleGraph: "Price source",
  question: (source: string) => source,
  noQuestion: "print proof not linked yet",
  settling: "the closing print lands 5–17 s after expiry; a cross-checked Window can wait up to 2 min for its check print.",
  noPosition: { why: "You held nothing in this window — nothing to stamp." },
  connect: { why: "Connect a wallet to see your verdict." },
  notFound: { why: "This window is gone.", nextAction: { label: "Pick a live window", href: "/markets" } },
  /** The claim card's words — reference `ClaimWinnings.tsx`; the footnote states our fact, not its keeper's. */
  claim: {
    notThisTime: "Not this time",
    lossBody: "The Window closed on the other side of your line.",
    youWon: "You won",
    claimed: "Claimed",
    profit: "Profit",
    ret: "return",
    stake: "Stake",
    payout: "Payout",
    collect: "Collect it now",
    collecting: "Collecting…",
    paid: "Paid to your wallet",
    /** The settler's `redeem_for` after the 300 s claim grace (D-032): the payout reached the wallet with no signature. */
    paidAuto: "Paid automatically",
    paidTx: "payout tx",
    foot: "Collect it with one signature now, or the venue pays it to your wallet automatically a few minutes after settlement.",
    /** Q-S6-7: a void is not "You won" — the reference's trophy branch is only a loss's opposite (M `ClaimWinnings.tsx:50-57`). */
    returned: "Returned",
    voidFoot: "Collect the returned 0.5 per contract with one signature now, or the venue pays it to your wallet a few minutes after settlement.",
  },
  devTitle: "Verdict moment",
  devEyebrow: "?m=<marketId> stamps a live window for the connected wallet",
  fixtures: {
    win: "Win — 正夢 in vermilion; the P&L figure is the only green",
    loss: "Loss — 逆夢 in neutral ink; a fact, not a scare",
    void: "Void — 無効; no reliable print, both sides pay 0.5",
    both: "Both sides held — one card, net P&L, both legs listed",
  },
} as const;

export const CLAIM = {
  claimable: "claimable",
  claimAll: "Claim all",
  retry: "Claim the rest",
  title: "Claim everything",
  pageIntro: "Claim a win with one signature per Window, paid to your wallet only. Unclaimed, the venue pays it to your wallet a few minutes after settlement.",
  waiting: (n: number) => (n === 0 ? "Nothing waiting right now" : `${n} settled ${n === 1 ? "Window" : "Windows"} waiting`),
  netLabel: "net of the settlement fee",
  feeNote: (bps: number) => (bps === 0 ? "fee 0% — read from chain" : `fee ${(bps / 100).toString()}% — read from chain`),
  oneSignatureEach: "One signature per Window — every leg in it is paid together, and each Window reports its own outcome.",
  contracts: "contracts",
  closed: "closed",
  settled: "settled",
  kind: {
    win: "Win",
    void: "Void — no reliable print, both sides pay 0.5",
    "vault-credit": "Vault credit — withdrawal",
  },
  leg: { up: "UP leg", down: "DOWN leg" },

  status: {
    pending: "waiting",
    claiming: "claiming…",
    confirmed: "claimed",
    paid: "paid to your wallet already",
    reverted: "reverted — nothing moved",
    unknown: "unknown — check the explorer",
  },
  progress: (current: number, total: number) => `claiming ${current} of ${total}`,
  finished: (claimed: number, total: number) => (claimed === total ? `Claimed ${claimed} of ${total}` : `${claimed} of ${total} claimed — the rest stayed put`),
  stopped: "Stopped early — every remaining item is untouched.",
  receipt: {
    title: "Claim receipt",
    figureLabel: "Paid to your wallet",
    settlement: "settlement tx",
    oracle: "Price source",
    pending: "…",
    settlementDegraded: "settlement tx not indexed yet — redemption tx only",
    oracleDegraded: "print proof not linked yet — raw tx only",
  },
  empty: { why: "Nothing to claim — winnings land here the moment a Window you're in settles." },
  disconnected: { why: "Connect a wallet to see what's waiting for it." },
  dev: {
    title: "Claim-all plate",
    intro: "Canned rows for every claim state, then the live plate for the connected wallet.",
    plate: "Plate, idle",
    progress: "Mid-run — one reverted, one signing",
    receipt: "Success receipt",
    live: "Live — your wallet",
  },
} as const;
