/**
 * Microsoft Fluent Emoji 3D (MIT, Copyright (c) Microsoft Corporation), vendored from
 * microsoft/fluentui-emoji @ `1ffb34c`. Provenance: `web/public/art/fluent/SOURCES.md`.
 */
export const FLUENT = {
  oldKey: { src: "/art/fluent/old-key.webp", w: 256, h: 256 },
  key: { src: "/art/fluent/key.webp", w: 256, h: 256 },
  bell: { src: "/art/fluent/bell.webp", w: 256, h: 256 },
  locked: { src: "/art/fluent/locked.webp", w: 256, h: 256 },
  ticket: { src: "/art/fluent/ticket.webp", w: 256, h: 256 },
  admissionTickets: { src: "/art/fluent/admission-tickets.webp", w: 256, h: 256 },
  coin: { src: "/art/fluent/coin.webp", w: 256, h: 256 },
  moneyWithWings: { src: "/art/fluent/money-with-wings.webp", w: 256, h: 256 },
  moneyBag: { src: "/art/fluent/money-bag.webp", w: 256, h: 256 },
  dollarBanknote: { src: "/art/fluent/dollar-banknote.webp", w: 256, h: 256 },
  redPaperLantern: { src: "/art/fluent/red-paper-lantern.webp", w: 256, h: 256 },
  redEnvelope: { src: "/art/fluent/red-envelope.webp", w: 256, h: 256 },
  hourglassNotDone: { src: "/art/fluent/hourglass-not-done.webp", w: 256, h: 256 },
  stopwatch: { src: "/art/fluent/stopwatch.webp", w: 256, h: 256 },
  crystalBall: { src: "/art/fluent/crystal-ball.webp", w: 256, h: 256 },
  chartIncreasing: { src: "/art/fluent/chart-increasing.webp", w: 256, h: 256 },
  chartDecreasing: { src: "/art/fluent/chart-decreasing.webp", w: 256, h: 256 },
  rocket: { src: "/art/fluent/rocket.webp", w: 256, h: 256 },
  gameDie: { src: "/art/fluent/game-die.webp", w: 256, h: 256 },
  slotMachine: { src: "/art/fluent/slot-machine.webp", w: 256, h: 256 },
  bullseye: { src: "/art/fluent/bullseye.webp", w: 256, h: 256 },
  trophy: { src: "/art/fluent/trophy.webp", w: 256, h: 256 },
  crown: { src: "/art/fluent/crown.webp", w: 256, h: 256 },
  fire: { src: "/art/fluent/fire.webp", w: 256, h: 256 },
  sparkles: { src: "/art/fluent/sparkles.webp", w: 256, h: 256 },
  eyes: { src: "/art/fluent/eyes.webp", w: 256, h: 256 },
  seeNoEvilMonkey: { src: "/art/fluent/see-no-evil-monkey.webp", w: 256, h: 256 },
  shushingFace: { src: "/art/fluent/shushing-face.webp", w: 256, h: 256 },
  ninja: { src: "/art/fluent/ninja.webp", w: 256, h: 256 },
  bentoBox: { src: "/art/fluent/bento-box.webp", w: 256, h: 256 },
  fishCakeWithSwirl: { src: "/art/fluent/fish-cake-with-swirl.webp", w: 256, h: 256 },
  cherryBlossom: { src: "/art/fluent/cherry-blossom.webp", w: 256, h: 256 },
  japaneseDolls: { src: "/art/fluent/japanese-dolls.webp", w: 256, h: 256 },
  windChime: { src: "/art/fluent/wind-chime.webp", w: 256, h: 256 },
  moonViewingCeremony: { src: "/art/fluent/moon-viewing-ceremony.webp", w: 256, h: 256 },
  cloud: { src: "/art/fluent/cloud.webp", w: 256, h: 256 },
  sun: { src: "/art/fluent/sun.webp", w: 256, h: 256 },
  star: { src: "/art/fluent/star.webp", w: 256, h: 256 },
  glowingStar: { src: "/art/fluent/glowing-star.webp", w: 256, h: 256 },
  partyPopper: { src: "/art/fluent/party-popper.webp", w: 256, h: 256 },
  confettiBall: { src: "/art/fluent/confetti-ball.webp", w: 256, h: 256 },
  gemStone: { src: "/art/fluent/gem-stone.webp", w: 256, h: 256 },
  link: { src: "/art/fluent/link.webp", w: 256, h: 256 },
  mobilePhone: { src: "/art/fluent/mobile-phone.webp", w: 256, h: 256 },
  barChart: { src: "/art/fluent/bar-chart.webp", w: 256, h: 256 },
  joystick: { src: "/art/fluent/joystick.webp", w: 256, h: 256 },
  crossedSwords: { src: "/art/fluent/crossed-swords.webp", w: 256, h: 256 },
  shield: { src: "/art/fluent/shield.webp", w: 256, h: 256 },
  handshake: { src: "/art/fluent/handshake.webp", w: 256, h: 256 },
  megaphone: { src: "/art/fluent/megaphone.webp", w: 256, h: 256 },
  lightBulb: { src: "/art/fluent/light-bulb.webp", w: 256, h: 256 },
  magnifyingGlassTiltedLeft: { src: "/art/fluent/magnifying-glass-tilted-left.webp", w: 256, h: 256 },
} as const;

export type FluentName = keyof typeof FLUENT;
