/** The redesigned studio's words (S22, D-127). The limits' own sentences stay in `copy.ts` (`DESK.studio.limits`). */
export const STUDIO = {
  steps: [
    { label: "The basket", hint: "What it holds" },
    { label: "How strict", hint: "The limits" },
    { label: "Test read", hint: "One real check" },
    { label: "Create", hint: "One signature" },
  ],
  nav: { back: "Back", next: "Continue", nextWithoutRead: "Continue without a test read" },
  basket: {
    presetsAria: "Start from a basket",
    own: { title: "Build your own", body: "Pick any of the eight PreStocks companies and set each weight yourself." },
    members: (n: number) => (n === 1 ? "1 company" : `${n} companies`),
    week: "7 days",
    noLine: "No marks yet",
  },
  weights: {
    title: "Weights",
    companies: "Companies",
    companiesAria: "Add or remove a company",
    add: (name: string) => `Add ${name}`,
    remove: (name: string) => `Remove ${name}`,
    cap: (n: number) => `Up to ${n} companies`,
    even: "Even split",
    reset: "Reset to basket",
    allocated: "allocated",
    over: (pct: string) => `${pct} over`,
    under: (pct: string) => `${pct} left`,
    exact: "Adds up to 100%",
    cash: "Cash",
    sliderAria: (name: string) => `${name} weight`,
    none: "Pick at least one company.",
  },
  strictness: {
    title: "How strict",
    aria: "How strict the desk is",
    custom: "Custom",
    presets: {
      careful: { title: "Careful", line: "Wanders 3% · stops at −10% · 5% premium ceiling" },
      balanced: { title: "Balanced", line: "Wanders 5% · stops at −15% · 10% premium ceiling" },
      loose: { title: "Loose", line: "Wanders 8% · stops at −25% · 20% premium ceiling" },
    },
    moneyTitle: "Money limits",
    shapeTitle: "Shape and safety",
    program: "Enforced on-chain",
    code: "Enforced by the desk",
  },
  read: {
    streamTitle: "What one check does",
    working: "Reading your basket…",
    done: "Read complete",
    steps: [
      "Sign the mandate",
      "Read PreStocks prices for every company",
      "Quote each trade on Jupiter at your size, PreStocks' 1% fee counted",
      "Ask the one timing question",
      "Write the decision down and fingerprint it",
    ],
  },
  receipt: {
    title: "Your desk",
    split: "The split",
    limits: "Limits",
    starts: "Starts in",
    practice: "Practice",
    live: "Live",
    modeAria: "Where the desk starts",
  },
  firstSteps: { done: "Created" },
  side: { total: "of your practice balance" },
} as const;
