import { RANGE_NOT_DEPLOYED } from "@agari/core/range";

/**
 * Range — the reference's words from its Ticket (`Ticket624Drawer.tsx` range mode, L857–1030, L1257–1280),
 * facts adapted to DreamDEX: the band settles on the Window's own closing print from the OracleHub
 * (context/43), the odds are the house's from the Window's book and its measured volatility, and the
 * whole payout is set aside up front as the parlay's is.
 */
export const RANGE = {
  title: "Range",
  eyebrow: "Inside the band · or outside it",
  sections: {
    build: { number: "01", title: "Call a band", desc: "Pick a Window, set the band around the market, choose inside or outside." },
    rounds: { number: "02", title: "Your rounds", desc: "Each round settles the moment the oracle prints. Claim the instant it lands." },
    how: { number: "03", title: "How a range pays" },
  },
  how: [
    { n: "①", t: "One print decides it", d: "The Window closes on the oracle's print — the same number its Up/Down settles on. Inside the band pays inside; outside pays outside." },
    { n: "②", t: "Tighter pays more", d: "A narrow band is less likely to catch the close, so it pays a bigger multiple. The odds come from where the market sits now and how much it usually moves in the time left." },
    { n: "③", t: "Pre-funded payout", d: "The full payout is set aside up front, so it can never come up short. Settle and claim the instant the print lands — anyone can send the crank." },
  ],
  notDeployed: {
    eyebrow: "Range",
    title: "Range",
    body: "Predict that settlement lands inside or outside a real band. This is never mapped onto an ordinary up/down position — it needs its own funded outcome.",
    why: RANGE_NOT_DEPLOYED,
    dependency: "the range reserve program (planned after the hackathon deadline)",
  },
  connect: { title: "Connect your wallet to call a band", sub: "Any Solana wallet, or sign in with email. Test funds are free" },
  band: {
    /** D-119: the reserve prices around its own centre, which a quiet book can leave away from the spot. */
    spotOutside: (spot: string) => `${spot} is the live price, and your band does not cover it. The reserve prices this Window from the venue's own book, which has not traded near that price yet.`,
    /** The reference: "Winning range" · "BTC must finish inside". */
    label: "Winning range",
    mustFinish: (asset: string, side: "inside" | "outside") => `${asset} must finish ${side}`,
    from: "From",
    to: "To",
    now: (asset: string) => `${asset} now`,
    waiting: "Waiting for the oracle price…",
    width: "Range width",
    /** `usd` is already on the asset's grid — `$60`, `$2.00`. */
    span: (usd: string) => `${usd} span`,
    center: "Range center",
    atMarket: "At market price",
    offMarket: (usd: string, above: boolean) => `${usd} ${above ? "above" : "below"} market`,
    sliderLabel: (asset: string) => `Range center relative to the current ${asset} price`,
    sliderCentered: "Centered on market price",
    sliderOff: (usd: string, above: boolean) => `${usd} ${above ? "above" : "below"} market price`,
    drag: "Drag to move the range",
    /** The reference's "five dollars" on BTC's grid; the step in figures on any other. */
    lower: (step: string) => (step === "$5" ? "Move range five dollars lower" : `Move range ${step} lower`),
    higher: (step: string) => (step === "$5" ? "Move range five dollars higher" : `Move range ${step} higher`),
    recenter: "Recenter range on the market price",
    /** The reference's short tooltips (`Ticket624Drawer.tsx` L1006, L1016, L1025); the long strings above are the aria-labels. */
    lowerTitle: (step: string) => `Move range ${step} lower`,
    higherTitle: (step: string) => `Move range ${step} higher`,
    recenterTitle: "Recenter range",
    presetLabel: (key: string, label: string) => (key === "medium" ? "Balanced" : label),
    sideLabel: "Side",
    inside: "Inside",
    outside: "Outside",
  },
  builder: {
    yourWindow: "Your Window",
    pickWindow: "Pick a Window",
    loading: "Loading markets…",
    noWindows: "No live Windows",
    noWindowsBody: "Bands open on live Up/Down Windows with a minute or more left. The next one is moments away.",
    opening: "opening print",
    openingPending: "opening print pending",
  },
  ticket: {
    title: "Ticket",
    tag: "range",
    pays: "Pays",
    needBand: "Pick a Window to price a band.",
    /** The reference's status line under an empty ticket (L1105–1110). */
    enterAmount: "Enter an amount to quote.",
    releaseToPrice: "Release to price this range.",
    odds: (pct: string, side: "inside" | "outside") => `${pct}% chance it lands ${side}`,
    setStake: "Set stake",
    setPayout: "Set payout",
    /** The open's cap is the quote plus a small headroom; the contract charges the exact stake at that second. */
    upTo: (amount: string, symbol: string) => `up to ${amount} ${symbol} if the basis moves before it lands`,
    youPay: "You pay",
    youWin: "You win",
    wallet: (balance: string, symbol: string) => `Wallet: ${balance} ${symbol}`,
    ifLands: "If the print lands your side",
    profit: (amount: string, symbol: string) => `${amount} ${symbol} profit if it lands`,
    retry: "Retry",
    placing: "Placing range…",
    placed: "Range placed!",
    pricing: "Pricing…",
    unavailable: "Quote unavailable",
    insufficient: (symbol: string) => `Insufficient ${symbol}`,
    place: (stake: string, symbol: string) => `Place · ${stake} ${symbol}`,
    build: "Set your band",
    footnote: "The full payout is set aside up front. Your stake leaves your wallet, and the rest is covered for you.",
    reserve: (liquid: string, symbol: string, utilizationPct: string) => `Reserve: ${liquid} ${symbol} liquid · ${utilizationPct}% in play`,
    reservePaused: "The reserve is paused: no new rounds until it reopens. Settlement and claims still run.",
    basis: (opening: string, centerPct: string) => `Opening print ${opening} · the book puts ${centerPct}% on a close above it`,
    tryAgain: "Try again",
    technical: "technical details",
    viewTx: "View on Solana Explorer",
    toast: (band: string, stake: string, payout: string, symbol: string) => `Range placed. ${band}: ${stake} to ${payout} ${symbol} if it lands.`,
    requote: (stake: string, symbol: string) => `The basis moved — this band now costs ${stake} ${symbol}. Confirm again to place it at the new price.`,
  },
  /** The reference's CTA: "Place RANGE $X to $Y →". */
  cta: {
    place: (from: string, to: string) => `Place RANGE ${from} to ${to} →`,
    placePlain: "Place RANGE →",
    /** The reference's footnote: "Gas-free · settles on its own, right on the price." — no sponsor here. */
    footnote: "Settles on its own, right on the oracle's print.",
    placed: (band: string) => `Range placed ${band}. Settles on the Window's closing print.`,
    rounds: "See your rounds",
    another: "Place another",
  },
  slip: {
    round: (asset: string, cadence: string) => `${asset} ${cadence}`,
    inPlay: "In play",
    won: "Won",
    lost: "Missed",
    voided: "Voided",
    paid: "Paid",
    band: (from: string, to: string, side: "inside" | "outside") => `${side} ${from} – ${to}`,
    /** A Moonshot row: the one edge that matters, in Pips' words for the side. */
    target: (direction: "long" | "short", strike: string) => (direction === "long" ? `long · above ${strike}` : `short · below ${strike}`),
    opening: (print: string) => `opened at ${print}`,
    closed: (print: string, inside: boolean) => `closed at ${print} · ${inside ? "inside" : "outside"} the band`,
    closedTarget: (print: string, hit: boolean) => `closed at ${print} · ${hit ? "past the target" : "short of the target"}`,
    settle: "Settle",
    settling: "Settling…",
    voidStale: "Void (no oracle answer)",
    voiding: "Voiding…",
    claim: (amount: string, symbol: string) => `Claim ${amount} ${symbol}`,
    claiming: "Claiming…",
    claimed: (amount: string, symbol: string, hash: string) => `Claimed ${amount} ${symbol} · ${hash}…`,
    settled: "Round settled.",
    voidedToast: "Round voided. Your stake is back in your wallet.",
    lostNote: "The print landed on the other side. Stake lost.",
    voidedNote: "The oracle voided the print, so the round is void. Your stake is back in your wallet.",
    paidNote: "Paid out to your wallet.",
    emptyConnected: "No rounds yet. Call a band above",
    emptyDisconnected: "Connect to see your rounds",
  },
  devTitle: "Range",
} as const;
