/** Words for the guest-seat surfaces: the account menu, the pool plates and the seat link (L-02, C-ADD-03, C-ADD-10). */
export const SEAT = {
  devTitle: "Guest seat",
  menu: {
    open: "Open seat menu",
    seat: (n: number | null) => (n === null ? "Guest seat" : `Guest seat ${n}`),
    leased: "Yours",
    draining: "Closing",
    unleased: "No party",
    unleasedNote: "This seat has no party on the ledger right now, so it cannot trade. Leasing one takes a second.",
    lease: "Lease a party",
    leasing: "Leasing…",
    party: "Party id",
    copyParty: "Copy party id",
    copied: "Copied",
    leaseLeft: "Lease left",
    leaseNote: "Renews while you use it; open calls keep it past the timer.",
    drainingNote: "Calls on Windows still trading are closed out at what you paid, fee included; decided calls settle as usual. Then the seat's credits go back to the venue and the seat returns to the pool.",
    tradingAccount: "Demo cash",
    portfolio: "Portfolio",
    link: "Use on another device",
    reset: "Reset seat",
  },
  pool: {
    fullTitle: "All guest seats are taken",
    fullBody: "Prices and markets stay live while you wait. This page will take the next free seat for you.",
    nextFrees: "Next frees in",
    inLine: (n: number) => (n === 1 ? "You are next in line" : `${n} ahead of you`),
    waiting: "Waiting",
    drainingTitle: "This seat is closing",
    drainingBody: "Its calls on Windows still trading are closed out at what was paid, fee included, and decided calls settle as usual. Then any cash is swept and the seat returns to the pool.",
    openCalls: (n: number) => (n === 1 ? "1 call still open" : `${n} calls still open`),
    closing: "Closing",
    lastSettles: "Last call settles in",
  },
  link: {
    title: "Use this seat on another device",
    subtitle: "Scan the code with your phone's camera, or type it on the other device.",
    manual: "Can't scan? Enter this code:",
    code: "Seat link code",
    copy: "Copy code",
    copied: "Copied",
    expiresIn: "Expires in",
    expired: "This code expired",
    expiredBody: "Codes last 60 seconds and work once.",
    fresh: "Show a new code",
    linkedTitle: "Linked",
    linkedBody: (device: string, n: number) => `${device} now uses Guest seat ${n}. Both devices see the same positions.`,
    qrAlt: "QR code that opens this seat on another device",
    joinTitle: "Joining from this device instead?",
    joinBody: "Enter the code shown on the device that already has the seat.",
    joinLabel: "Seat link code",
    join: "Join that seat",
    joining: "Waiting for the other device to allow this one…",
    joinHint: "Eight letters and numbers, from the other screen. That device then allows this one.",
    confirmTitle: "Allow this device?",
    confirmBody: (key: string, n: number) => `A device with key ${key} used this code and wants Guest seat ${n}. Allow it only if it is yours.`,
    allow: "Allow",
    decline: "Not mine",
    deciding: "Answering…",
    declinedTitle: "Not allowed",
    declinedBody: "That device was not added. Show a new code for a device of yours.",
    joinDeclined: "The other device did not allow this one.",
    joinError: "That code has expired or was already used. Ask the other device for a new one.",
    joinSuccess: "Joined. This device now uses that seat.",
    foot: "A code links one device, once. Reset the seat on either device to end the link.",
  },
} as const;
