/**
 * Microsoft Fluent Emoji 3D (MIT, Copyright (c) Microsoft Corporation), the same objects as the web
 * manifest (`web/src/lib/art/fluent.ts`), vendored from microsoft/fluentui-emoji @ `1ffb34c`.
 */
export const FLUENT = {
  oldKey: { src: require("../../../assets/art/fluent/old-key.png") as number, w: 256, h: 256 },
  key: { src: require("../../../assets/art/fluent/key.png") as number, w: 256, h: 256 },
  bell: { src: require("../../../assets/art/fluent/bell.png") as number, w: 256, h: 256 },
  locked: { src: require("../../../assets/art/fluent/locked.png") as number, w: 256, h: 256 },
  ticket: { src: require("../../../assets/art/fluent/ticket.png") as number, w: 256, h: 256 },
  admissionTickets: { src: require("../../../assets/art/fluent/admission-tickets.png") as number, w: 256, h: 256 },
  coin: { src: require("../../../assets/art/fluent/coin.png") as number, w: 256, h: 256 },
  moneyWithWings: { src: require("../../../assets/art/fluent/money-with-wings.png") as number, w: 256, h: 256 },
  moneyBag: { src: require("../../../assets/art/fluent/money-bag.png") as number, w: 256, h: 256 },
  dollarBanknote: { src: require("../../../assets/art/fluent/dollar-banknote.png") as number, w: 256, h: 256 },
  redPaperLantern: { src: require("../../../assets/art/fluent/red-paper-lantern.png") as number, w: 256, h: 256 },
  redEnvelope: { src: require("../../../assets/art/fluent/red-envelope.png") as number, w: 256, h: 256 },
  hourglassNotDone: { src: require("../../../assets/art/fluent/hourglass-not-done.png") as number, w: 256, h: 256 },
  stopwatch: { src: require("../../../assets/art/fluent/stopwatch.png") as number, w: 256, h: 256 },
  crystalBall: { src: require("../../../assets/art/fluent/crystal-ball.png") as number, w: 256, h: 256 },
  chartIncreasing: { src: require("../../../assets/art/fluent/chart-increasing.png") as number, w: 256, h: 256 },
  chartDecreasing: { src: require("../../../assets/art/fluent/chart-decreasing.png") as number, w: 256, h: 256 },
  rocket: { src: require("../../../assets/art/fluent/rocket.png") as number, w: 256, h: 256 },
  gameDie: { src: require("../../../assets/art/fluent/game-die.png") as number, w: 256, h: 256 },
  slotMachine: { src: require("../../../assets/art/fluent/slot-machine.png") as number, w: 256, h: 256 },
  bullseye: { src: require("../../../assets/art/fluent/bullseye.png") as number, w: 256, h: 256 },
  trophy: { src: require("../../../assets/art/fluent/trophy.png") as number, w: 256, h: 256 },
  crown: { src: require("../../../assets/art/fluent/crown.png") as number, w: 256, h: 256 },
  fire: { src: require("../../../assets/art/fluent/fire.png") as number, w: 256, h: 256 },
  sparkles: { src: require("../../../assets/art/fluent/sparkles.png") as number, w: 256, h: 256 },
  eyes: { src: require("../../../assets/art/fluent/eyes.png") as number, w: 256, h: 256 },
  seeNoEvilMonkey: { src: require("../../../assets/art/fluent/see-no-evil-monkey.png") as number, w: 256, h: 256 },
  shushingFace: { src: require("../../../assets/art/fluent/shushing-face.png") as number, w: 256, h: 256 },
  ninja: { src: require("../../../assets/art/fluent/ninja.png") as number, w: 256, h: 256 },
  bentoBox: { src: require("../../../assets/art/fluent/bento-box.png") as number, w: 256, h: 256 },
  fishCakeWithSwirl: { src: require("../../../assets/art/fluent/fish-cake-with-swirl.png") as number, w: 256, h: 256 },
  cherryBlossom: { src: require("../../../assets/art/fluent/cherry-blossom.png") as number, w: 256, h: 256 },
  japaneseDolls: { src: require("../../../assets/art/fluent/japanese-dolls.png") as number, w: 256, h: 256 },
  windChime: { src: require("../../../assets/art/fluent/wind-chime.png") as number, w: 256, h: 256 },
  moonViewingCeremony: { src: require("../../../assets/art/fluent/moon-viewing-ceremony.png") as number, w: 256, h: 256 },
  cloud: { src: require("../../../assets/art/fluent/cloud.png") as number, w: 256, h: 256 },
  sun: { src: require("../../../assets/art/fluent/sun.png") as number, w: 256, h: 256 },
  star: { src: require("../../../assets/art/fluent/star.png") as number, w: 256, h: 256 },
  glowingStar: { src: require("../../../assets/art/fluent/glowing-star.png") as number, w: 256, h: 256 },
  partyPopper: { src: require("../../../assets/art/fluent/party-popper.png") as number, w: 256, h: 256 },
  confettiBall: { src: require("../../../assets/art/fluent/confetti-ball.png") as number, w: 256, h: 256 },
  gemStone: { src: require("../../../assets/art/fluent/gem-stone.png") as number, w: 256, h: 256 },
  link: { src: require("../../../assets/art/fluent/link.png") as number, w: 256, h: 256 },
  mobilePhone: { src: require("../../../assets/art/fluent/mobile-phone.png") as number, w: 256, h: 256 },
  barChart: { src: require("../../../assets/art/fluent/bar-chart.png") as number, w: 256, h: 256 },
  joystick: { src: require("../../../assets/art/fluent/joystick.png") as number, w: 256, h: 256 },
  crossedSwords: { src: require("../../../assets/art/fluent/crossed-swords.png") as number, w: 256, h: 256 },
  shield: { src: require("../../../assets/art/fluent/shield.png") as number, w: 256, h: 256 },
  handshake: { src: require("../../../assets/art/fluent/handshake.png") as number, w: 256, h: 256 },
  megaphone: { src: require("../../../assets/art/fluent/megaphone.png") as number, w: 256, h: 256 },
  lightBulb: { src: require("../../../assets/art/fluent/light-bulb.png") as number, w: 256, h: 256 },
  magnifyingGlassTiltedLeft: { src: require("../../../assets/art/fluent/magnifying-glass-tilted-left.png") as number, w: 256, h: 256 },
} as const;

export type FluentName = keyof typeof FLUENT;
