/**
 * The abu-pm-main Daml package as TypeScript: `PM.<Module>.<Template>` companions (template ids, choices, JSON
 * codecs) and their types, generated by `dpm codegen-js` into ../generated and re-exported here so the import path
 * never carries the Daml package version.
 *
 *   import { PM, TEMPLATE_IDS } from "@agari/daml";
 *   PM.Quote.Quote.templateId            // "#abu-pm-main:PM.Quote:Quote" (package-name reference)
 *   PM.Quote.Quote.templateIdWithPackageId // "#<packageId>:PM.Quote:Quote" (pinned to this build)
 *   type Quote = PM.Quote.Quote;          // the contract payload
 */
import { PM, packageId } from "@daml.js/abu-pm-main";

export { PM, packageId };

/** The Daml package name every package-name template id refers to. */
export const DAML_PACKAGE_NAME = "abu-pm-main";

/** Package-name template ids (`#abu-pm-main:Module:Entity`), keyed by entity, for ledger filters and the projector. */
export const TEMPLATE_IDS = {
  Series: PM.Series.Series.templateId,
  MarketTerms: PM.Market.MarketTerms.templateId,
  WindowState: PM.Market.WindowState.templateId,
  OpenPrint: PM.Market.OpenPrint.templateId,
  Resolution: PM.Market.Resolution.templateId,
  PriceQuote: PM.Oracle.PriceQuote.templateId,
  VenueCash: PM.Money.VenueCash.templateId,
  VenueAccount: PM.Money.VenueAccount.templateId,
  VenueAccountInvite: PM.Money.VenueAccountInvite.templateId,
  VenueDesk: PM.Quote.VenueDesk.templateId,
  Quote: PM.Quote.Quote.templateId,
  BuyQuote: PM.Quote.BuyQuote.templateId,
  Leg: PM.Leg.Leg.templateId,
  NettedResidual: PM.Leg.NettedResidual.templateId,
  Publication: PM.Publication.Publication.templateId,
  GrantOffer: PM.Grant.GrantOffer.templateId,
  AgentGrant: PM.Grant.AgentGrant.templateId,
  NavStatement: PM.Reserve.NavStatement.templateId,
  LpShare: PM.Reserve.LpShare.templateId,
  SupplyQuote: PM.Reserve.SupplyQuote.templateId,
  WithdrawQuote: PM.Reserve.WithdrawQuote.templateId,
} as const;

export type TemplateName = keyof typeof TEMPLATE_IDS;
