/**
 * The abu-pm-main Daml package as TypeScript: `PM.<Module>.<Template>` companions (template ids, choices, JSON
 * codecs) and their types, generated by `dpm codegen-js` into ../generated and re-exported here so the import path
 * never carries the Daml package version.
 *
 *   import { PM, TEMPLATE_IDS } from "@agari/daml";
 *   PM.Quote.Quote.templateId            // "#abu-pm-main:PM.Quote:Quote" (package-name reference)
 *   PM.Quote.Quote.templateIdWithPackageId // "#<packageId>:PM.Quote:Quote" (pinned to this build)
 *   type Quote = PM.Quote.Quote;          // the contract payload
 */
import { PM, packageId } from "@daml.js/abu-pm-main";
import * as Tickets from "@daml.js/abu-pm-tickets";
import * as Agents from "@daml.js/abu-pm-agents";
import * as Games from "@daml.js/abu-pm-games";

export { PM, packageId };

/** The Daml package name every package-name template id refers to. */
export const DAML_PACKAGE_NAME = "abu-pm-main";

/** Package-name template ids (`#abu-pm-main:Module:Entity`), keyed by entity, for ledger filters and the projector. */
export const TEMPLATE_IDS = {
  Series: PM.Series.Series.templateId,
  MarketTerms: PM.Market.MarketTerms.templateId,
  WindowState: PM.Market.WindowState.templateId,
  OpenPrint: PM.Market.OpenPrint.templateId,
  Resolution: PM.Market.Resolution.templateId,
  PriceQuote: PM.Oracle.PriceQuote.templateId,
  VenueCash: PM.Money.VenueCash.templateId,
  VenueAccount: PM.Money.VenueAccount.templateId,
  VenueAccountInvite: PM.Money.VenueAccountInvite.templateId,
  VenueDesk: PM.Quote.VenueDesk.templateId,
  Quote: PM.Quote.Quote.templateId,
  BuyQuote: PM.Quote.BuyQuote.templateId,
  Leg: PM.Leg.Leg.templateId,
  NettedResidual: PM.Leg.NettedResidual.templateId,
  Publication: PM.Publication.Publication.templateId,
  SettlementReceipt: PM.Publication.SettlementReceipt.templateId,
  GrantOffer: PM.Grant.GrantOffer.templateId,
  AgentGrant: PM.Grant.AgentGrant.templateId,
  NavStatement: PM.Reserve.NavStatement.templateId,
  LpShare: PM.Reserve.LpShare.templateId,
  SupplyQuote: PM.Reserve.SupplyQuote.templateId,
  WithdrawQuote: PM.Reserve.WithdrawQuote.templateId,
  // 0.4.0 (K-030): committee yes/no events.
  EventTerms: PM.Event.EventTerms.templateId,
  EventState: PM.Event.EventState.templateId,
  EventAttestation: PM.Event.EventAttestation.templateId,
  EventVerdict: PM.Event.EventVerdict.templateId,
  // 0.5.0 (K-092, K-200): the maker vault's book and its on-ledger statement.
  MakerDesk: PM.Maker.MakerDesk.templateId,
  BookReceipt: PM.Book.BookReceipt.templateId,
  // 0.5.1 (K-235): the pre-open resting call.
  RestingDesk: PM.Resting.RestingDesk.templateId,
  RestingOffer: PM.Resting.RestingOffer.templateId,
  RestingCall: PM.Resting.RestingCall.templateId,
} as const;

export type TemplateName = keyof typeof TEMPLATE_IDS;

/**
 * The abu-pm-tickets package (C8): range and moonshot rounds, boosts and shorts, parlays, the per-reserve `RiskBook`
 * and the Earn desk. A second namespace beside `PM`, since both packages declare modules under `PM.*`.
 *
 *   import { Tickets, TICKET_TEMPLATE_IDS } from "@agari/daml";
 *   Tickets.PM.Tickets.Range.RangeRound.templateId  // "#abu-pm-tickets:PM.Tickets.Range:RangeRound"
 */
export { Tickets };

export const TICKETS_PACKAGE_NAME = "abu-pm-tickets";

const T = Tickets.PM.Tickets;

/** Package-name template ids of abu-pm-tickets, kept apart from `TEMPLATE_IDS` so nothing that walks those changes. */
export const TICKET_TEMPLATE_IDS = {
  RiskBook: T.Book.RiskBook.templateId,
  EarnDesk: T.Earn.EarnDesk.templateId,
  RangeQuote: T.Range.RangeQuote.templateId,
  RangeRound: T.Range.RangeRound.templateId,
  BoostQuote: T.Boost.BoostQuote.templateId,
  BoostPosition: T.Boost.BoostPosition.templateId,
  BoostExitQuote: T.Boost.BoostExitQuote.templateId,
  ParlayQuote: T.Parlay.ParlayQuote.templateId,
  ParlayTicket: T.Parlay.ParlayTicket.templateId,
} as const;

export type TicketTemplateName = keyof typeof TICKET_TEMPLATE_IDS;

/**
 * The abu-pm-agents package (C8f): grants' desk, the strategy registry and the agent desk. A fourth namespace beside
 * `PM`, `Tickets` and `Games`, since it too declares modules under `PM.*`.
 *
 *   import { Agents, AGENT_TEMPLATE_IDS } from "@agari/daml";
 *   Agents.PM.Agents.Desk.DeskMandate.templateId  // "#abu-pm-agents:PM.Agents.Desk:DeskMandate"
 */
export { Agents };

export const AGENTS_PACKAGE_NAME = "abu-pm-agents";

const A = Agents.PM.Agents;

/** Package-name template ids of abu-pm-agents. */
export const AGENT_TEMPLATE_IDS = {
  GrantDesk: A.Vault.GrantDesk.templateId,
  CreatorLicense: A.Strategy.CreatorLicense.templateId,
  Strategy: A.Strategy.Strategy.templateId,
  StrategyListing: A.Strategy.StrategyListing.templateId,
  SubscriberInvite: A.Strategy.SubscriberInvite.templateId,
  SubscriberBook: A.Strategy.SubscriberBook.templateId,
  Subscription: A.Strategy.Subscription.templateId,
  StrategyFee: A.Strategy.StrategyFee.templateId,
  CreatorPayout: A.Strategy.CreatorPayout.templateId,
  DeskOffer: A.Desk.DeskOffer.templateId,
  DeskMandate: A.Desk.DeskMandate.templateId,
  DeskDecision: A.Desk.DeskDecision.templateId,
  DeskMark: A.Desk.DeskMark.templateId,
} as const;

export type AgentTemplateName = keyof typeof AGENT_TEMPLATE_IDS;

/**
 * The abu-pm-games package (C9): the duel arena (commit-reveal checked on the ledger with `DA.Text.sha256`), the
 * match's record of each seat's call, and the season prize pool. A third namespace beside `PM` and `Tickets`.
 *
 *   import { Games, GAMES_TEMPLATE_IDS } from "@agari/daml";
 *   Games.PM.Games.Arena.DuelMatch.templateId  // "#abu-pm-games:PM.Games.Arena:DuelMatch"
 */
export { Games };

export const GAMES_PACKAGE_NAME = "abu-pm-games";

const G = Games.PM.Games;

/** Package-name template ids of abu-pm-games, kept apart from `TEMPLATE_IDS` so nothing that walks those changes. */
export const GAMES_TEMPLATE_IDS = {
  ArenaTerms: G.Arena.ArenaTerms.templateId,
  DuelOpen: G.Arena.DuelOpen.templateId,
  DuelMatch: G.Arena.DuelMatch.templateId,
  DuelResult: G.Arena.DuelResult.templateId,
  SeasonPool: G.Season.SeasonPool.templateId,
} as const;

export type GamesTemplateName = keyof typeof GAMES_TEMPLATE_IDS;
