import { PRIVATE_HONESTY, PRIVATE_NOT_DEPLOYED } from "@agari/core/private";

/**
 * The private route — the reference's own words where it has them (`Ticket624Drawer.tsx` L1175–1247: the
 * Public/Private control, the budget line, "Always 1x."; `PrivateClaims.tsx`: the claims list and its backup
 * copy; `MOBILE_INTEGRATION.md` §5: the honest one-liner) and the desk's real facts where it showed none.
 * Never "anonymous", "untraceable" or "zk" — link-reduction is what this is (doc 00 §No-substitution).
 */
export const PRIVATE = {
  route: {
    label: "Private",
    titleReady: PRIVATE_HONESTY,
    titleProbing: "Checking private mode…",
    titleUnavailable: (reason: string) => `Private mode is not available right now: ${reason}`,
    titleOverCap: (cap: string) => `Private bets are capped at ${cap}`,
    titleRange: "Private bets cannot be range bets. Switch to Up or Down, or turn Private off.",
    retry: "retry",
  },
  /** The reference's exact chip title. */
  chipsLocked: "Private bets are placed at 1x.",
  note: {
    balance: (amount: string) => `${amount} in your private balance.`,
    empty: "Private bets spend a balance only you can withdraw.",
    addFunds: "add funds",
    adding: "adding…",
    reallow: (balance: string, allowance: string) => `${balance} in your private balance, but the desk may spend only ${allowance} of it.`,
    reallowAction: "re-allow",
    pending: (window: string) => `A private bet on ${window} is still waiting for the chain. The next tap resumes it — nothing is charged twice.`,
    /** The reference: "Always 1x. Cash out from this device." — the claim lives in this browser, and the list is on Portfolio. */
    always: "Always 1×. Cash out from this browser, on Portfolio.",
    honesty: PRIVATE_HONESTY,
    signatures: "Adding funds is a transaction (two signatures the first time); the bet itself is one signature more, and moves nothing by itself.",
  },
  cta: {
    buy: (side: string) => `Buy ${side} privately for`,
    buyPlain: "Buy privately for",
    fundAndBuy: (amount: string, side: string) => `Add ${amount} and buy ${side} privately`,
    reallowAndBuy: (side: string) => `Re-allow and buy ${side} privately`,
    resume: (window: string) => `Resume the private bet on ${window}`,
    notPlaced: "Private bet not placed",
  },
  quote: {
    cost: "Cost",
    payoutIfRight: (side: string) => `Payout if ${side} lands`,
    maxLoss: "Max loss",
    odds: "Odds",
    sized: (charged: string, symbol: string) => `Sized off the live book: ${charged} ${symbol} buys the contracts; the rest waits in the slot and comes home with the payout.`,
  },
  toasts: {
    placed: (side: string, window: string) => `Private bet placed: ${side} on ${window}`,
    refunded: (amount: string, symbol: string) => `${amount} ${symbol} is back in your private balance.`,
    toppedUp: "Private balance topped up. Only you can withdraw it.",
    unknown: "The chain has not answered yet — tap again to resume; nothing is charged twice.",
    flippedOff: (reason: string) => `Private mode went away (${reason}); this bet would come from your wallet. Choose Private again once it is back.`,
    resumed: (window: string) => `Resumed: the private bet on ${window} was already placed.`,
    cashedOut: (amount: string, symbol: string) => `Cashed out: ${amount} ${symbol} credited to your private balance.`,
    lost: "Settled — that one lost. Whatever the slot still held is back in your private balance.",
    stillOpen: "Not settled yet — cash out once the Window closes.",
    alreadyHome: "Already credited to your private balance.",
    withdrawn: "Private balance withdrawn to your wallet.",
    revoked: "The desk's allowance is revoked; your balance is untouched.",
    deposited: "Private balance topped up. Only you can withdraw it.",
  },
  /** `PrivateClaims.tsx`, verbatim but for the brand and the signer — a desk key the contract pins, not an attested enclave. */
  claims: {
    emptyTitle: "No private positions yet",
    emptySub: "Turn on Private before you place a bet and your address stays off the position.",
    title: "Private positions",
    sub: "Only you hold the proof these are yours.",
    backUp: "Back up",
    restore: "Restore",
    restored: (n: number, skipped: number) => `Restored ${n} claim${n === 1 ? "" : "s"}.${skipped > 0 ? ` ${skipped} row${skipped === 1 ? "" : "s"} in the file could not be read and ${skipped === 1 ? "was" : "were"} skipped.` : ""}`,
    skipped: (n: number) => `${n} row${n === 1 ? "" : "s"} in that file could not be read; nothing was restored.`,
    home: (amount: string, symbol: string) => `${amount} ${symbol} came home`,
    nothingNew: "Nothing new in that file.",
    unreadable: "That file could not be read.",
    warn: "One of these was not signed by the desk key the contract pins, so cashing it out is blocked. That usually means the file it was restored from was edited, or the desk key was rotated. Restore from a clean backup.",
    checking: "Checking",
    verified: "Verified",
    verifiedTitle: "Signed by the desk key the contract pins",
    unverified: "Unverified",
    unverifiedTitle: "This claim was not signed by the desk key the contract pins",
    cashOut: "Cash out",
    cashingOut: "Cashing out",
    open: "open",
    settled: "settled",
    credited: "credited",
    foot: "Keep your backup somewhere safe. Nobody at Agari can rebuild these for you, which is the same reason nobody there can read them.",
    fileName: (date: string) => `agari-private-claims-${date}.json`,
    just: "just now",
    minutes: (m: number) => `${m}m ago`,
    hours: (h: number) => `${h}h ago`,
    days: (d: number) => `${d}d ago`,
  },
  panel: {
    eyebrow: "Private balance",
    note: "Private bets spend from this, inside the limit you set. Only you can withdraw it.",
    amountLabel: "Private balance amount",
    deposit: "Deposit",
    depositing: "Depositing",
    withdraw: "Withdraw",
    withdrawing: "Withdrawing",
    revoke: "Revoke",
    revoking: "Revoking",
    revokeNote: "stops private bets; the balance stays yours",
    cells: { balance: "Balance", allowance: "Desk may spend", spendable: "Spendable", desk: "Desk key", cap: "Per bet, at most" },
    approvalNote: "Two signatures this first time: approve tUSDC, then the deposit.",
    allowanceNote: "A deposit allows the desk the whole new balance.",
    trust: "The desk moves what you allow into a bet and the payout back to this balance; only your wallet withdraws. A stolen desk key could redirect what you allowed it, so the allowance is the most at risk — keep it to a few bets.",
    correlation: "What stays visible: the charge and the slot's funding land seconds apart for the same figure. Someone determined can line them up.",
  },
  pool: {
    label: "Private",
    note: "Private bets spend from this. Only you can withdraw it.",
  },
  notDeployed: {
    why: PRIVATE_NOT_DEPLOYED,
    how: "A record in contracts/deployments, or the NEXT_PUBLIC_PRIVATE_DESK_ADDRESS override, connects it. Public bets keep working.",
  },
  devTitle: "Private",
} as const;
