import { PRIVATE_HONESTY, PRIVATE_NOT_DEPLOYED } from "@agari/core/private";

/**
 * The private route — the reference's own words where it has them (`Ticket624Drawer.tsx` L1175–1247: the
 * Public/Private control, the budget line, "Always 1x."; `PrivateClaims.tsx`: the claims list and its backup
 * copy; `MOBILE_INTEGRATION.md` §5: the honest one-liner) and the desk's real facts where it showed none.
 * Never "anonymous", "untraceable" or "zk" — link-reduction is what this is (doc 00 §No-substitution).
 */
export const PRIVATE = {
  route: {
    label: "Private",
    titleReady: PRIVATE_HONESTY,
    titleProbing: "Checking private mode…",
    titleUnavailable: (reason: string) => `Private mode is not available right now: ${reason}`,
    titleOverCap: (cap: string) => `Private bets are capped at ${cap}`,
    titleRange: "Private bets cannot be range bets. Switch to Up or Down, or turn Private off.",
    retry: "retry",
  },
  /** The reference's exact chip title. */
  chipsLocked: "Private bets are placed at 1x.",
  note: {
    balance: (amount: string) => `${amount} in your private balance.`,
    empty: "Private bets spend a balance only you can withdraw.",
    addFunds: "add funds",
    adding: "adding…",
    reallow: (balance: string, allowance: string) => `${balance} in your private balance, but the desk may spend only ${allowance} of it.`,
    reallowAction: "re-allow",
    pending: (window: string) => `A private bet on ${window} is still waiting for the chain. The next tap resumes it — nothing is charged twice.`,
    /** The reference: "Always 1x. Cash out from this device." On Canton (0.5.2, K-315) the settle pays the private balance itself. */
    always: "Always 1×. The payout comes back to your private balance when the Window settles.",
    honesty: PRIVATE_HONESTY,
    signatures: "Adding funds moves demo credits from your seat's balance in one ledger write; the bet itself is one signature more, and moves nothing by itself.",
  },
  cta: {
    buy: (side: string) => `Buy ${side} privately for`,
    buyPlain: "Buy privately for",
    fundAndBuy: (amount: string, side: string) => `Add ${amount} and buy ${side} privately`,
    reallowAndBuy: (side: string) => `Re-allow and buy ${side} privately`,
    resume: (window: string) => `Resume the private bet on ${window}`,
    notPlaced: "Private bet not placed",
  },
  quote: {
    cost: "Cost",
    payoutIfRight: (side: string) => `Payout if ${side} lands`,
    maxLoss: "Max loss",
    odds: "Odds",
    sized: (charged: string, symbol: string) => `Sized off the venue's live ladder: ${charged} ${symbol} buys the contracts, paid from your private balance alone.`,
  },
  toasts: {
    placed: (side: string, window: string) => `Private bet placed: ${side} on ${window}`,
    refunded: (amount: string, symbol: string) => `${amount} ${symbol} is back in your private balance.`,
    toppedUp: "Private balance topped up. Only you can withdraw it.",
    unknown: "The chain has not answered yet — tap again to resume; nothing is charged twice.",
    flippedOff: (reason: string) => `Private mode went away (${reason}); this bet would come from your seat. Choose Private again once it is back.`,
    resumed: (window: string) => `Resumed: the private bet on ${window} was already placed.`,
    cashedOut: (amount: string, symbol: string) => `Cashed out: ${amount} ${symbol} credited to your private balance.`,
    lost: "Settled — that one lost. Nothing came back; the call is closed.",
    stillOpen: "Not settled yet — cash out once the Window closes.",
    alreadyHome: "Already credited to your private balance.",
    withdrawn: "Private balance withdrawn to your seat.",
    revoked: "The desk's allowance is revoked; your balance is untouched.",
    deposited: "Private balance topped up. Only you can withdraw it.",
  },
  /** `PrivateClaims.tsx`, verbatim but for the brand and the signer — a desk key the contract pins, not an attested enclave. */
  claims: {
    emptyTitle: "No private positions yet",
    emptySub: "Turn on Private before you place a call and it stays off everything your seat can make public.",
    title: "Private positions",
    sub: "Your seat's own calls, tagged private on the ledger: seen only by your seat and the venue.",
    backUp: "Back up",
    restore: "Restore",
    restored: (n: number, skipped: number) => `Restored ${n} claim${n === 1 ? "" : "s"}.${skipped > 0 ? ` ${skipped} row${skipped === 1 ? "" : "s"} in the file could not be read and ${skipped === 1 ? "was" : "were"} skipped.` : ""}`,
    skipped: (n: number) => `${n} row${n === 1 ? "" : "s"} in that file could not be read; nothing was restored.`,
    home: (amount: string, symbol: string) => `${amount} ${symbol} came home`,
    nothingNew: "Nothing new in that file.",
    unreadable: "That file could not be read.",
    warn: "One of these was not signed by the desk key the contract pins, so cashing it out is blocked. That usually means the file it was restored from was edited, or the desk key was rotated. Restore from a clean backup.",
    checking: "Checking",
    verified: "On the ledger",
    verifiedTitle: "Your seat's own leg, tagged private; only your seat and the venue can see it",
    unverified: "Unverified",
    unverifiedTitle: "This claim was not signed by the desk key the contract pins",
    cashOut: "Cash out",
    cashingOut: "Cashing out",
    open: "open",
    settled: "settled",
    credited: "credited",
    /** 0.5.2 (K-315): the ledger's receipt says the payout landed in the private bucket at settlement. */
    paidPrivate: "in private balance",
    paidPrivateTitle: "The venue paid this call straight back into your private balance; the ledger's receipt names the bucket",
    foot: "The venue settles each call at its Window's close and pays it straight back into your private balance; a call settled before that change shows Cash out, which brings it home once. Never published, never on a leaderboard.",
    fileName: (date: string) => `agari-private-claims-${date}.json`,
    just: "just now",
    minutes: (m: number) => `${m}m ago`,
    hours: (h: number) => `${h}h ago`,
    days: (d: number) => `${d}d ago`,
  },
  panel: {
    eyebrow: "Private balance",
    note: "Private calls spend from this, and only private calls do. Only you can move it back to your seat.",
    amountLabel: "Private balance amount",
    deposit: "Deposit",
    depositing: "Depositing",
    withdraw: "Withdraw",
    withdrawing: "Withdrawing",
    revoke: "Revoke",
    revoking: "Revoking",
    revokeNote: "stops private bets; the balance stays yours",
    cells: { balance: "Balance", allowance: "Desk may spend", spendable: "Spendable", inCalls: "In open calls", desk: "Desk key", cap: "Per call, at most" },
    approvalNote: "Two signatures this first time: approve credits, then the deposit.",
    allowanceNote: "A deposit moves demo credits from your seat's balance; Withdraw moves them all back.",
    trust: "Moving credits in or out is one transaction your seat and the venue sign together, so nothing moves unless both halves do. A private call is your seat's own leg, paid only from this balance.",
    correlation: "What stays visible: the venue sees every call, private or not, as the counterparty. Private keeps a call off your public record, not off the venue's books.",
  },
  pool: {
    label: "Private",
    note: "Private calls spend from this. Only you can move it back to your seat.",
  },
  notDeployed: {
    why: PRIVATE_NOT_DEPLOYED,
    how: "The private route answers from this deployment's seat tier; until it does, public calls keep working.",
  },
  devTitle: "Private",
} as const;
