/**
 * The record, one decision in full, Check it, the watcher's notifications and the desk's hooks into other pages
 * (plan §5.7 item 7, §5.8, §5.9, §5.2). Plain words; the desk's own first-person lines come from core `deskCopy`.
 */
export const RECORD = {
  list: {
    title: "The record",
    intro: "One entry for every check, including the ones that found nothing to do. Those are the proof it was awake.",
    back: "← Your desk",
    empty: "Nothing recorded yet.",
    quiet: (n: number, from: string, to: string) => `${n} quiet checks · ${from}–${to}`,
    older: "Older →",
    seq: (n: number) => `#${n}`,
    practiceTag: "practice",
  },
  outcome: {
    acted: "Acted",
    acted_in_part: "Acted in part",
    acted_by_override: "Acted on your call",
    would_have_acted: "Would have acted",
    asked: "Asked you",
    nothing_to_do: "Nothing to do",
    not_executed: "Not carried out",
    waited: "Waited",
    declined: "Decided not to",
    blocked_by_limit: "Stopped by a limit",
    failed: "Could not decide",
  } as const,
  decision: {
    back: "← the whole record",
    sections: {
      decision: "The decision",
      why: "Why it looked",
      saw: "What it saw",
      options: "The options it weighed",
      limits: "The limits check",
      cost: "The cost, shown before acting",
      happened: "What happened",
      proof: "Proof",
      now: "How it looks now",
    },
    what: "What",
    when: "When",
    mode: "Mode",
    howSure: "How sure",
    noModel: "no model was asked",
    routine: "A routine hourly check.",
    trigger: { hourly: "A routine hourly check.", deposit: "Money arrived in the desk.", move: (name: string, pct: string) => `${name} moved ${pct} within an hour.`, check_now: "You pressed Check now.", test_read: "Your test read from the studio." } as Record<string, string | ((name: string, pct: string) => string)>,
    deferral: (seq: number) => `It had already decided this at #${seq}.`,
    deferralStanding: "Nothing measurable had changed since, so it did not ask again.",
    approvalOf: (seq: number, when: string, moved: string) => `You approved this in #${seq}, answered ${when}. The price had moved ${moved} since it was shown.`,
    override: (by: string, reason: string) => `Overruled by ${by}: ${reason}`,
    saw: {
      price: "PreStocks token price",
      ageSec: (sec: number) => (sec < 60 ? `${sec} s old` : `${Math.round(sec / 60)} min old`),
      ageUnknown: "age unknown",
      mark: "Its mark",
      premium: (pct: string) => `${pct} above its mark`,
      discount: (pct: string) => `${pct} below its mark`,
      index: "Pyth's valuation index",
      mean: "Half-hour average",
      gap: (pct: string) => `spot ${pct} from its average`,
      inLine: "in line with its average",
      drift: (weight: string, target: string, threshold: string) => `${weight} of the desk against a target of ${target}, allowed to wander ${threshold}`,
      cost: "What this trade costs at your size",
      costValue: (pct: string) => `${pct}, PreStocks' 1% included`,
      costNone: "no quote at this size",
      route: (n: number) => `${n} accounts in the route`,
      status: "Transfers",
      paused: "paused by PreStocks",
      pauseUnknown: "could not be confirmed",
      open: "open",
      frozen: "the desk's account is frozen",
      limitsLeft: "Your limits left",
      limitsLine: (perAction: string, left: string, cash: string) => `${perAction} per action · ${left} left today · ${cash} cash in the desk`,
      reference: "Venue reference",
      fresh: "fresh",
      stale: "stale",
      nothing: "Nothing to see: the desk found no candidate, so it read no market.",
      blockers: "Stopped before any question was asked",
    },
    options: {
      ACT_NOW: "Do it now",
      ACT_PART: "Do part of it now",
      WAIT: "Wait",
      DECLINE: "Do not do it",
      chosen: "chosen",
      turnedDown: "turned down",
      part: (pct: number) => `${pct}% of it`,
      waitFor: (what: string) => `Waiting for: ${what}`,
      noModel: "No model was asked.",
      warnings: "It noted",
    } as const,
    limits: {
      arithmetic: "This part is plain arithmetic, not an assistant. It can refuse, and it can never start anything.",
      passed: "Every limit passed.",
      refused: (reasons: string) => `Refused: ${reasons}.`,
      nothing: "Nothing to check: the desk was not going to act.",
      counted: "Counted against your limits",
      floor: "The least it would accept",
      premiumOk: "Premium check",
      ok: "passed",
      no: "refused",
    },
    cost: { spend: "It would spend", receive: "It should receive", least: "The least it would accept", slippage: "Slippage allowed", deadline: "Deadline" },
    happened: {
      nothingSent: "Nothing was sent.",
      practice: "Practice: nothing is ever sent. The paper ledger moved instead.",
      received: (actual: string, expected: string) => `received ${actual} against ${expected} expected`,
      failed: (code: string) => `Failed: ${code}`,
      explorer: "Solana Explorer ↗",
      paperAfter: "The paper ledger after this check",
    },
    proof: {
      own: "The fingerprint of this record was written on Solana mainnet in the same transaction as the action it describes. Nobody can change the record now without the change being visible.",
      later: (seq: number) => `This record did nothing on the chain, so it has no transaction of its own. Record #${seq} was written on Solana later, and every record in between names the fingerprint of the one before it, so that fingerprint commits to this record too.`,
      unsealed: "This record is not on Solana yet. The next action or checkpoint writes a fingerprint that commits to it.",
      practice: "A practice desk has no on-chain account, so there is no chain to compare with. The fingerprint is still recomputed here, exactly as it is for a live desk.",
      fingerprint: "fingerprint",
    },
    grade: {
      same: "No real difference either way.",
      better: (pct: string) => `Waiting was better by ${pct}.`,
      betterActed: (pct: string) => `Acting then was better than waiting by ${pct}.`,
      worse: (pct: string) => `Acting at once would have been better by ${pct}.`,
      worseActed: (pct: string) => `Waiting would have been better by ${pct}.`,
      ungradable: "This one cannot be graded.",
      notYet: "Not yet. Each decision is graded a day later, against the price the alternative would really have got.",
    },
  },
  checkIt: {
    check: "Check it",
    checking: "Asking Solana mainnet…",
    download: "Download this record",
    showBytes: "Show the exact bytes",
    hideBytes: "Hide the exact bytes",
    before: "Your browser will rebuild this record's fingerprint from the bytes below, then ask Solana mainnet for the fingerprint it holds and compare the two. The chain is asked from your browser; nothing goes through us.",
    beforePractice: "Your browser will rebuild this record's fingerprint from the bytes below and compare it with the one stored beside the record.",
    beforeUnsealed: "Your browser can rebuild this record's fingerprint from the bytes below. It is not on Solana yet.",
    computed: "your browser computed",
    stored: "stored with the record",
    onChain: "held by Solana mainnet",
    seeTx: "see the transaction",
    matches: "It matches. The fingerprint your browser computed is the one Solana holds. Nobody has changed this record since it was written, including us.",
    storedMatches: "It matches the fingerprint stored with the record.",
    storedMismatch: "It does NOT match even the fingerprint stored with it. Something is wrong on our side.",
    mismatch: "It does NOT match. Solana holds a different fingerprint. Do not trust this record as shown.",
    noEvent: "The transaction holds no fingerprint for this desk. Do not trust this record as shown.",
    unreachable: "The bytes match the fingerprint stored with the record, but your browser could not reach Solana to compare. Open the transaction and compare the fingerprint yourself.",
    links: (n: number, seq: number) => `Your browser rebuilt the ${n} ${n === 1 ? "record" : "records"} up to #${seq} and checked that each names the fingerprint of the one before it.`,
    linkOk: (seq: number) => `#${seq} names the one before it and hashes as it should`,
    linkBroken: (seq: number) => `#${seq} does NOT match: the chain of records is broken here`,
  },
  watcher: {
    title: (outcome: string) => `Your desk: ${outcome}`,
    money: "Your desk: money moved",
    foot: "Test nothing: this is your real desk on Solana mainnet.",
    practiceFoot: "Practice: nothing moved.",
  },
  og: {
    alt: "A shared Agari desk: its mode, how many checks are on its record, and its last check.",
    eyebrow: "A shared desk",
    title: "Someone's desk",
    checks: (n: number) => `${n} ${n === 1 ? "check" : "checks"} on the record`,
    lastCheck: (ago: string) => `Last check ${ago}`,
    noCheck: "No check yet",
    live: "Solana mainnet",
    practice: "Practice",
  },
  hooks: {
    stocks: { inWallet: (tokens: string) => `In your wallet ${tokens}`, inDesk: (tokens: string) => `In your desk ${tokens}`, hold: "Let a desk hold this basket", holdWhy: "A desk holds the basket for you with real money on Solana mainnet, inside your limits." },
    agents: { body: "Strategies bet test money on Windows for you. Your desk holds real PreStocks tokens for you.", cta: "Open your desk →" },
    reel: { badge: "YOUR DESK", title: "Your desk", voice: (line: string) => line, cta: "Read the decision →", foot: "Your own desk's latest decision, from its record." },
    sensei: { starter: "Why did my desk wait?" },
    tutorial: " A desk can also hold a basket of PreStocks for you, with real money, inside your limits.",
  },
} as const;
