/**
 * The controls, the money sheets and Go live (plan §5.5, §5.7 item 9). Each control shows a card first: what changes,
 * Now → After, who signs, when it expires; nothing happens until it is confirmed. The network is named on every card
 * that can move money. Banned-word checked with the rest (`copy.test.ts`).
 */
export const CONTROLS = {
  title: "Controls",
  intro: "Each one shows you a card first. Nothing happens until you confirm it.",
  actions: {
    addMoney: "Add money",
    withdraw: "Withdraw",
    sellAll: "Sell everything",
    pause: "Pause",
    resume: "Resume",
    mode: "Mode",
    checkNow: "Check now",
    share: "Share",
    close: "Close the desk",
  },
  card: {
    who: { wallet: "Your seat signs one Canton command", message: "Your seat signs one message; nothing moves", request: "Your seat signs one message; the desk carries it out at its next check" },
    now: "Now",
    after: "After",
    expires: (when: string) => `This card expires ${when}.`,
    confirm: "Confirm",
    notNow: "Not now",
    confirming: "Confirm with your seat…",
    sending: "Sent. Waiting for the ledger…",
    done: "Done.",
    doneTx: "Done. See it on the proof page ↗",
    failed: (why: string) => `Not done: ${why}`,
    left: "Left alone. Nothing changed.",
    expired: "This card expired. Open it again.",
    unsupported: "This request is not carried by the desk index yet. Nothing changed.",
  },
  pause: { title: "Stop the desk acting", body: "Nothing is sold. It stops until you resume it, and waiting requests are cancelled. Your withdrawals still work while it is paused.", now: (state: string) => `Desk ${state}`, after: "Desk paused by you" },
  resume: { title: "Let the desk carry on", body: "It carries on from its next check. If it was stopped by your loss limit, the limit counts from what the desk is worth now.", after: "Desk active" },
  mode: { title: "How much the desk does on its own", body: "The mode is written into your desk's contract, so the ledger refuses what the mode forbids.", now: (mode: string) => `Mode: ${mode}`, after: (mode: string) => `Mode: ${mode}`, practiceLocked: "A practice desk has one mode. Go live to choose Ask me first or On its own." },
  checkNow: { title: "Look at everything now", body: "The desk checks now and decides as it always does. It may still choose to wait. Once every ten minutes.", after: "A check within the minute", throttled: (until: string) => `It checked a moment ago. It can look again at ${until}.` },
  share: { title: "A read-only link", body: "Anyone with the link sees the desk's holdings and record, never your notes. Turn it off at any time.", on: "Sharing is on", off: "Sharing is off", link: "Copy the link", copied: "Copied" },
  sellAll: { title: "Turn every holding into cash", body: "Every position the desk holds is sold back to the venue at its next check, and the cash stays in the desk. Nothing leaves your account.", after: "Every holding sold to USDC at the next check" },
  close: { title: "Close this desk for good", body: "The desk sells every holding, sends everything to your own seat and stops the checks. The record stays readable. Two signatures: the request, then the operator is revoked from your account.", after: "Desk closed; everything on its way to your seat" },
  editMandate: { title: "Change the mandate", body: "A new version, signed by you. Waiting approvals are cancelled and the change applies from the next check." },
} as const;

export const MONEY = {
  sheetTitle: "Put money in",
  eyebrow: "LIVE DESK",
  intro: "Money goes straight to the desk's own account, never through Agari. Only you can take it out.",
  network: "Your seat signs one Canton command. No network fee.",
  usdc: { title: "Cash from your seat", amount: "Amount in USDC", have: (amount: string) => `Your seat holds ${amount} USDC.`, none: "Your seat holds no USDC yet. Add demo credits to your seat first." },
  tokens: { title: "Companies come in by the desk buying them", none: "A company comes into the desk only when the desk buys it, and leaves when it sells or its hourly Window settles into your seat.", row: (tokens: string, name: string) => `${tokens} ${name}`, all: "all" },
  receipt: { send: "You send", receive: "Your desk receives", fee: "PreStocks' 1% transfer fee", networkFee: "Network fee", networkFeeValue: "none on Canton", takes: "Takes", seconds: "seconds", leaves: (amount: string, symbol: string) => `${amount} ${symbol} leaves`, arrives: (amount: string, symbol: string) => `${amount} ${symbol} arrives` },
  tooSmall: (min: string) => `Under ${min} is too small: the fixed fees of each trade take too large a share.`,
  noSol: { line: "Canton charges no network fee: opening a desk and each action cost nothing to send.", link: "How seats work ↗" },
  send: "Confirm with your seat",
  sending: "Confirm with your seat…",
  reading: "Reading your seat on the ledger…",
  unreadable: "Your seat could not be read on the ledger just now.",
  withdraw: {
    title: "Take money out",
    body: "It goes to your own seat, and nowhere else. That address is fixed by your account and cannot be changed here.",
    to: "To",
    some: "Some",
    all: "Everything",
    amount: "Amount in USDC",
    asCash: "As cash: the desk sells first, then you withdraw",
    asTokens: "As tokens: each holding goes to your seat as it is",
    usdcInDesk: (amount: string) => `${amount} USDC is in the desk now.`,
    cashNote: "Selling first is a request to the desk; the cash is then yours to withdraw with one confirmation per holding.",
    perMint: (n: number) => `${n} confirmation${n === 1 ? "" : "s"}, one per holding`,
    button: "Withdraw",
  },
  deposited: (amount: string, symbol: string) => `${amount} ${symbol} is in your desk. It is put to work at the next check.`,
  withdrawn: (symbol: string) => `${symbol} is back in your seat.`,
} as const;

export const GO_LIVE = {
  title: "Go live",
  eyebrow: "LIVE DESK",
  body: "Four steps, each one command your seat signs on Canton. Every step can be resumed if you close the page.",
  steps: {
    open: { title: "Open the desk on Canton", body: (perAction: string, daily: string, premium: string) => `Creates your desk with the ledger's limits: ${perAction} per action, ${daily} a day, buys at most ${premium} above the mark.`, button: "Open the live desk" },
    allow: { title: "Allow the basket's companies", body: (names: string) => `Tells the desk's contract which companies' hourly Windows it may buy: ${names}.`, button: "Allow the companies" },
    attach: { title: "Link the desk to its record", body: "One signed message, no transaction: your practice record continues as the live desk's.", button: "Sign the link" },
    deposit: { title: "Put money in", body: "Cash from your seat. The desk buys the companies itself.", button: "Open the money sheet" },
  },
  mode: "It goes live in",
  resume: (step: string) => `Resuming at: ${step}`,
  done: "Your desk is live on Canton.",
  noOperator: "This deployment has no desk operator configured, so a desk cannot be opened here yet.",
  unsupported: (why: string) => why,
  fees: "No network fee: Canton charges nothing to open a desk or for any action.",
} as const;

export const DESK_ERRORS_UI = {
  notConfigured: "The desk index is not configured on this deployment. Practice desks and the record need it.",
  noWallet: "Take a seat first.",
  signCancelled: "You cancelled. Nothing changed.",
  refused: (status: number, why: string) => `${why} (${status})`,
  unknown: "Something did not go through. Nothing was sent twice.",
} as const;
