/**
 * Every word the desk's studio, page, controls and money sheets show (S21 C5, plan §5). Plain words, first person
 * for what the desk did (its own lines come from core `deskCopy`), "cover" never "hedge", "mark" and "above its
 * mark" for the premium, the network named every time money can move. `copy.test.ts` runs the banned-word rule over
 * all of it. The record's, decision's, Check it's and watcher's words live in `copy-record.ts`.
 */
export const DESK = {
  eyebrow: {
    live: "YOUR DESK · SOLANA MAINNET · REAL MONEY",
    practice: "YOUR DESK · PRACTICE · NO MONEY MOVES",
    visitorLive: "SOMEONE ELSE'S DESK · SOLANA MAINNET · READ-ONLY",
    visitorPractice: "SOMEONE ELSE'S DESK · PRACTICE · READ-ONLY",
    studio: "DESK STUDIO · PRACTICE FIRST",
  },
  title: "Your desk",
  /** The same page read by someone who is not the owner. */
  visitorTitle: "A desk",
  titleJp: "机に任せる。",
  visitor: "Someone else's desk. You are reading it; nothing here can be changed from this page.",
  network: { live: "Phantom will show a Solana mainnet transaction.", practice: "No transaction. Practice moves no money." },
  modes: { practice: "Practice", ask_first: "Ask me first", on_its_own: "On its own" } as const,
  modeNote: {
    practice: "It decides for real, on real prices and real quotes, and spends nothing.",
    ask_first: "It asks you before every action and does nothing until you answer.",
    on_its_own: "It acts inside your limits without asking, and still asks above your large-action size.",
  } as const,
  state: {
    active: "active",
    practice: "in practice",
    paused_by_owner: "paused by you",
    stopped_by_loss_limit: "stopped by your loss limit",
    needs_attention: "waiting for attention",
    closed: "closed",
  } as const,
  tabs: { desk: "Desk", record: "Record" },

  studio: {
    kicker: "Desk studio",
    title: "Tell the desk what to hold.",
    body: "Pick a basket, set the limits, hear the desk read it back, then create it. You decide what; the desk decides only when; the program enforces the money limits.",
    steps: ["The basket", "How strict, and the limits", "The test read", "Create"] as const,
    stepsAria: "Creation progress",
    back: "← Back",
    next: "Continue →",
    nextWithoutRead: "Continue without a test read →",
    edit: { kicker: "Edit the mandate", title: "Change what the desk holds.", body: "A new mandate version. Waiting approvals are cancelled, and the change applies from the next check." },
    basket: {
      presets: "Start from a basket",
      weights: "Weights",
      cash: "Cash sleeve",
      cashNote: "Cash waits in the desk as USDC and is what the desk buys with.",
      total: (pct: string) => `${pct} of 100%`,
      mustAddUp: "The weights and the cash must add up to 100%.",
      side: (amount: string, parts: string) => `${amount} → ${parts}`,
      fromBasket: (name: string) => `Picked from the ${name} basket. Change anything.`,
    },
    limits: {
      title: "How strict",
      drift: (pct: string) => `May wander ${pct} before it acts`,
      driftFloor: (pct: string) => `A trade costs about 1.1% each way, so the desk waits for at least ${pct} of drift whatever you set here.`,
      position: (pct: string) => `One company may be at most ${pct} of the desk`,
      perAction: (usd: string) => `Most in one action ${usd}`,
      daily: (usd: string) => `Most in a day ${usd}`,
      premium: (pct: string) => `Never buy a company more than ${pct} above its mark`,
      loss: (pct: string) => `Stop everything after a fall of ${pct}`,
      large: (usd: string) => `Ask me first above ${usd}`,
      program: "The program enforces this",
      code: "The desk's own code enforces this",
      programNote: "Per action, per day, the premium ceiling and which companies are allowed are written into your account on Solana. The desk cannot go past them whatever it decides.",
      codeNote: "Drift, the largest share and the loss stop are checked by the desk's own code before anything is sent.",
      notes: "Anything in your own words",
      notesHint: "For example: never buy on a Sunday. It shapes when the desk acts, never how much and never what it holds. Only you ever see it.",
      count: (n: number, max: number) => `${n} / ${max}`,
    },
    read: {
      title: "Read my basket now",
      body: "One real cycle, no money: real PreStocks prices, real Jupiter quotes at your size, PreStocks' 1% fee counted, the one AI question asked and answered. Signing the mandate starts your practice desk with a practice balance; nothing moves.",
      practiceCash: "Practice balance",
      practiceCashNote: "Pretend money the desk counts with. Change it to the amount you would really put in.",
      run: "Read my basket now",
      again: "Read it again",
      signing: "Sign the mandate in your wallet…",
      waiting: "The desk is reading your basket. Real prices, real quotes, one AI question; about a minute.",
      throttled: (until: string) => `The desk already checked a moment ago. It looks again at ${until}, or at the next check.`,
      first: "The first decision",
      heard: "Here is how I understood you",
      question: "One question",
      connect: "Connect the wallet the desk will belong to. Practice needs no tokens and no mainnet.",
      failed: "The desk could not read it just now. You can continue and it reads at the next check.",
      exists: "Your desk already exists; this read applies the mandate as a new version.",
    },
    create: {
      title: "Create your desk",
      practice: { title: "Practice", body: "One signature. The desk exists as a record with a practice balance. Every hour it reads real prices and writes down what it would have done. No transaction, no money, no eligibility.", button: "Sign and start in practice", done: "Your practice desk exists." },
      live: { title: "Live", body: "Open on Solana: one Phantom confirmation on mainnet creates an account that belongs to you. Then you put money in.", button: "Open on Solana mainnet", needsPractice: (n: number) => `Go live unlocks after ${n} practice checks and the record opened. Start in practice first.` },
      applied: "Mandate applied.",
      apply: "Sign the new version",
      connect: "Connect your wallet to sign. Signing costs nothing and moves nothing.",
      problems: "Before you sign:",
      unsupported: (why: string) => `Live needs mainnet: ${why}`,
    },
    firstSteps: {
      kicker: "Created",
      title: "Your desk exists.",
      body: "It belongs to your wallet. It checks every hour, on the hour, and writes every decision down.",
      steps: "First steps",
      money: { title: "Put money in", body: "USDC from this wallet, or PreStocks tokens you already hold. Money goes straight to the desk's own account, never through Agari." },
      goLive: { title: "The Go live rule", body: (n: number) => `${n} practice checks of your own and the record opened, then Go live is one mainnet transaction.` },
      notify: { title: "Turn on notifications", body: "The desk tells you when it acts, asks, or is stopped. Never for a quiet check.", on: "Notifications are on", turnOn: "Allow notifications", denied: "Notifications are blocked in this browser; the desk will tell you here instead." },
      open: "Open your desk →",
    },
    side: {
      kicker: "Your desk",
      preset: (name: string) => name,
      own: "Your own basket",
      perAction: "Most in one action",
      daily: "Most in a day",
      mode: "Starts in",
      read: "Test read",
      readDone: "Done for this draft",
      readStale: "Draft changed since",
      readNone: "Not yet",
      approach: "The desk's one approach: AI judges only timing; arithmetic decides everything else, and the program holds the money limits.",
    },
  },

  page: {
    needsYou: {
      title: "Needs you",
      nothing: "Nothing needs you.",
      asking: { ask_first: "Asking because you chose to be asked first.", large_action: "Asking because this one is above your large-action size." } as const,
      trade: (side: string, amountIn: string, expectedOut: string, name: string) => (side === "sell" ? `Sell ${amountIn} ${name} for about $${expectedOut}` : `Buy $${amountIn} of ${name} (about ${expectedOut} tokens)`),
      turnedDown: (what: string) => `It turned down: ${what}`,
      confidence: (pct: number) => `${pct}% sure of the timing`,
      cost: (pct: string) => `costs about ${pct}, PreStocks' 1% included`,
      expires: (when: string) => `expires ${when}`,
      expired: "Expired unanswered. Nothing was done.",
      approve: "Approve",
      decline: "Decline",
      approving: "Signing…",
      paused: "Paused by you. Nothing happens until you resume it.",
      lossStop: "Stopped by your loss limit. To carry on, press Resume in Controls; the limit then counts from what the desk is worth at that moment.",
      late: (ago: string) => `The desk has not checked in. Its last check was ${ago}. Your money is in your own account and cannot move without the operator.`,
      closed: "This desk is closed. Its record stays readable.",
    },
    plate: {
      title: "What it holds",
      total: "Total value",
      since: "Since your money went in",
      timing: "Timing",
      timingNote: "What the desk's timing calls earned or cost against acting at once, graded a day later. It can be negative.",
      timingNone: "Nothing graded yet. Each call is graded a day later.",
      timingValue: (pct: string, n: number) => `${pct} over ${n} graded ${n === 1 ? "call" : "calls"}`,
      valued: (age: string) => `Valued ${age} on the half-hour average of PreStocks' token price.`,
      notYet: "Not valued yet. The desk values itself at its first check.",
      practiceCash: (amount: string) => `Practice balance ${amount}. None of your money has moved.`,
    },
    nextCheck: {
      title: "Next check",
      lead: (clock: string, inText: string) => `At the top of the hour, ${clock} · in ${inText}`,
      note: { practice: "Real prices, no money moves.", ask_first: "Asks before it acts.", on_its_own: "Acts inside your limits." } as Record<string, string>,
      also: "Also on deposits and 3% moves.",
      lastCheck: (ago: string) => `Last check ${ago}.`,
      noCheck: "No check yet. The first one is at the top of the next hour.",
      checklist: "Before Go live",
      checksDone: (done: number, needed: number) => (done >= needed ? `${needed} practice checks done` : `${Math.min(done, needed)} of ${needed} practice checks done`),
      readRecord: "Read the record",
      recordRead: "Record read",
      open: "Open",
      goLive: "Go live",
    },
    holdings: {
      title: "Holdings",
      target: (pct: string) => `target ${pct}`,
      inLine: "in line",
      over: (pct: string) => `${pct} over`,
      under: (pct: string) => `${pct} under`,
      none: "Nothing held yet. Cash waits until the desk sees a reason to buy.",
      flags: {
        paused: "PreStocks has paused transfers of this token. The desk will not touch it until they resume.",
        frozen: "This account is frozen by the issuer. Nobody can move it until it is thawed.",
        stale: "Its price is stale. The desk will not trade it until a fresh one is read.",
        premium: (pct: string, ceiling: string) => `${pct} above its mark; your ceiling is ${ceiling}. The desk will not buy it.`,
        fast: "Its price is moving fast. The desk waits for it to settle.",
      },
      premium: (pct: string) => `${pct} above its mark`,
      discount: (pct: string) => `${pct} below its mark`,
    },
    cash: { title: "Cash", line: (amount: string) => `${amount} USDC in the desk`, practiceLine: (amount: string) => `${amount} practice USDC` },
    limits: {
      title: "Limits in use",
      spentToday: "Spent today",
      spentOf: (spent: string, cap: string) => `${spent} of ${cap}`,
      perAction: "Most in one action",
      premium: "Premium ceiling",
      loss: "Loss stop",
      large: "Asks first above",
      practiceNote: "In practice nothing is spent, so the daily line stays at zero.",
    },
    record: { title: "The record", whole: "The whole record →", empty: "The desk has not checked yet.", quiet: (n: number, from: string, to: string) => `${n} quiet checks · ${from}–${to}` },
    mandate: {
      title: "The mandate",
      version: (n: number) => `version ${n}`,
      basket: "The basket",
      notes: "Your notes",
      noNotes: "No notes.",
      edit: "Edit →",
      editNote: "Editing makes a new version and cancels waiting approvals.",
    },
  },

  promise: {
    title: "The promise",
    points: [
      "It is your account: only you can withdraw, and only to your wallet.",
      "It stays inside your limits, and the program itself enforces the money limits.",
      "It always explains itself, including every time it does nothing.",
      "The record cannot be quietly changed: its fingerprint is on Solana in the same transaction as the trade.",
      "You can stop it at any moment: Pause, Withdraw, Close.",
    ],
    worstCase: "Worst case, in one sentence: if the desk's key were ever stolen, the thief could only make bad trades, at most your daily limit a day, until you pause.",
  },
} as const;

export const DESK_ADVICE = "Not investment advice. A PreStocks token is a claim on a company's SPV, never a share. The desk makes no forecast and promises nothing.";
