/**
 * The X rail's words — ported from `reference/yosuku/app/trade-from-x/page.tsx`,
 * `components/XWalletCard.tsx` and `app/claim/page.tsx`, with the brand substituted and the
 * mechanics named as ours: an EXECUTOR grant on the EventVault instead of a tweet vault, a
 * signed wallet link instead of a tweeted code, and no leverage.
 */
import { SHARE } from "@/features/share/copy";

export const X_HANDLE = SHARE.handle;

export const X_LINK_STATUS = {
  checking: "Checking your X connection…",
  unavailable: "X sign-in is not available on this deployment yet.",
} as const;

export const X_ERRORS = {
  notConfigured: X_LINK_STATUS.unavailable,
  storeUnavailable: "The social store is not connected on this deployment.",
  signInFirst: "sign in with X first",
  invalidWallet: "invalid wallet",
  signatureRequired: "wallet signature required",
  signatureMismatch: "wallet signature did not match",
  staleSignature: "that signature is too old — sign again",
  alreadyLinkedOther: "already_linked_other",
  notLinked: "this X account is not linked to that wallet",
  badRequest: "bad request",
  linkFailed: "Could not link this wallet. Please try again.",
  unlinkFailed: "Could not disconnect X.",
} as const;

/** The reference's OAuth bounce messages (`XWalletCard.tsx` L400–412). */
export const X_OAUTH_MESSAGES: Record<string, string> = {
  denied: "X authorization was cancelled. Please try again.",
  state: "Your X sign-in session expired. Please try again.",
  token: "X could not complete the connection. Please try again.",
  profile: "X connected, but your profile could not be read. Please try again.",
  config: "X connection is temporarily unavailable.",
  server: "X connection is temporarily unavailable. Please try again.",
};
export const X_OAUTH_FALLBACK = "X authorization did not finish. Please try again.";
export const X_OAUTH_EXPIRED = "Your X approval expired before it could finish. Please connect again.";
export const xOauthRejected = (code: string) => `X rejected the connection (${code.replaceAll("_", " ")}). Please try again.`;

export const TRADE_FROM_X = {
  title: "Trade from X",
  crumb: "/ X-trade",
  openApp: "open the app",
  eyebrow: "X-trade",
  headline: "Trade by tweeting.",
  payoff: "Un⁠-⁠drainably.",
  lede: (handle: string) => [`Tweet your calls at `, handle, `. A bounded agent trades `, `your own`, ` funds, and can’t take them.`] as const,
  yourKeys: "your keys, your funds",
  venue: "Solana devnet · Agari order book",
  setup: "set it up · three steps",
  steps: { connect: "Connect your wallet", fund: "Fund + authorize the agent", link: "Link your X account" },
  connected: "connected",
  funded: "X trading enabled · funded balance is your spending boundary",
  linkLede: "Sign in with X, then sign once with your wallet to prove the handle is yours.",
  signIn: "Sign in with X",
  linkAs: (handle: string) => `Link @${handle} to this wallet`,
  linking: "Linking…",
  linked: (handle: string) => `@${handle} routes to this wallet`,
  errTail: "",
  then: "then · you’re live",
  justTweet: "Just tweet your calls.",
  opensFrom: "opens from your Trading Balance · settles back to you.",
  noWithdraw: "no withdraw path exists for the agent · verify:",
  proofs: {
    contract: "the vault pays only its owner — test_AD5_no_divert",
    caps: "every X order spends only from its allocated balance",
  },
  testnetNote: "devnet test funds · you can lose a call · the agent just can’t take your funds.",
  receipt: {
    lede: (amount: string, symbol: string) => [`Fund `, `${amount} ${symbol}`, `. Grant `, `one`, ` power: open a position you own.`] as const,
    amountAria: "Amount to fund",
    can: "can",
    canText: (amount: string, open: number) => [`trade from your funded balance: `, amount, ` total. No separate per-trade or daily spending limit. Up to `, `${open}`, ` open Windows.`] as const,
    cannot: "cannot",
    cannotStruck: "withdraw · transfer · drain",
    cannotTail: ". No such path for the agent.",
    line: (amount: string, symbol: string) => [`fund `, `${amount} ${symbol}`, ` · open-position only · revocable · 30 days`] as const,
    cta: "Fund and enable X trading",
    ctaApprove: "Fund and enable X trading",
    busy: "Confirm in your wallet…",
    notDeployed: "The Trading Balance contract is not deployed on this network yet.",
  },
  receipts: { title: "your receipts", empty: "No mentions executed yet.", none: "Receipts arrive once the relay is running." },
} as const;

export const X_CARD = {
  title: "X-Predict wallet",
  wrongWallet: (handle: string) => `Wrong wallet for @${handle}.`,
  itBetsFrom: "It bets from",
  connectedAs: ", and you are connected as",
  strandedNote: ". Funding this one would leave the money where no reply can spend it.",
  copyAddress: (short: string) => `Copy ${short}`,
  copied: "Address copied.",
  notInBrowser: "That wallet is not connected in this browser. Open the wallet that holds it and connect it here. Unlinking has to be signed by that wallet too, so it cannot be done from here.",
  switchQuestion: (from: string, to: string) => `Switch @${from} to @${to}?`,
  oneMoreStep: (handle: string) => `One more step to bet from @${handle}.`,
  switchNote: "Your balance stays here. Only which X account can bet changes.",
  useHandle: (handle: string) => `Use @${handle}`,
  linkHandle: (handle: string) => `Link @${handle} to this wallet`,
  linking: "Linking…",
  xConnected: "X connected",
  switchAccount: "Switch X account",
  disconnect: "Disconnect X",
  disconnecting: "Disconnecting…",
  verifyToDisconnect: "Verify to disconnect",
  linkToBet: "Link your X account to bet with this.",
  connectFirst: "Connect X first, then fund.",
  connectX: "Connect X",
  connectWallet: "Connect your wallet to fund your X betting balance.",
  balanceLabel: "Your X betting balance",
  cashOut: "Cash out",
  cashingOut: "Cashing out",
  fund: "Fund",
  funding: "Funding",
  amountAria: "Amount to fund",
  checking: "Checking…",
  howTo: (handle: string) => `Mention ${handle} with an asset, a side, a stake and a Window.`,
  funded: (amount: string, handle: string) => `Funded ${amount}. Mention ${handle} to bet it.`,
  cashedOut: (amount: string) => `Cashed out ${amount} to your Trading Balance.`,
  linkedOk: "Linked. Your mentions now bet from this balance.",
  unlinkedOk: (amount: string) => `X disconnected. Your ${amount} remains in this wallet's Trading Balance.`,
  nothingToCashOut: "Nothing to cash out yet.",
  enterAmount: "Enter an amount to fund.",
  notEnough: "Not enough collateral in your wallet. Grab some from the faucet on Markets first.",
  wrongWalletFund: "This X account bets from a different wallet. Connect that wallet before funding.",
  notDeployed: "The Trading Balance contract is not deployed on this network yet.",
  noExecutor: "Trading from X is temporarily unavailable. Please try again shortly.",
  budgetPolicy: "X trading can spend the balance you allocate here. No separate per-trade or daily spending limit. Only you can add funds or cash out.",
  balanceUnavailable: "Your X balance could not be verified. Refresh before making changes.",
  finishUpdate: "Update your existing X trading permission below before adding funds.",
  updateUnreadable: "Your saved X update could not be read. Check wallet activity before starting another update.",
  updated: "X trading updated. Your allocated balance is now the spending boundary.",
  availableShort: "There is not enough available in your Trading Balance for this amount.",
  depositReturned: "The deposit was confirmed. Check the top-up transaction before retrying; any unallocated funds remain in your Trading Balance.",
} as const;

export const CLAIM = {
  title: "Claim your account",
  eyebrow: "YOUR TRADING BALANCE",
  headlineKnown: "waiting",
  headline: ["Claim your", "winnings."] as const,
  ledeKnown: (handle: string | null) => (handle ? `It’s yours, @${handle}. Connect the wallet it routes to and it’s in your hands.` : "It’s yours. Connect the wallet it routes to and it’s in your hands."),
  lede: "You bet from a mention, so your calls landed in the Trading Balance of the wallet your X account routes to. Prove it’s you and we’ll show you which one.",
  steps: { prove: "Prove it’s you", where: "Which wallet is yours?" },
  signedInAs: (handle: string | null) => `signed in${handle ? ` as @${handle}` : ""}`,
  signIn: "Sign in with X",
  connected: (short: string) => `${short} connected`,
  linking: "· linking…",
  routesTo: (short: string) => `@your account routes to ${short}`,
  thisWallet: "This is the wallet. Your Trading Balance is on Portfolio.",
  otherWallet: (short: string) => `Your account routes to ${short}, not to this wallet. Connect that one to use its balance, or re-link below to route future mentions here.`,
  relink: (handle: string) => `Route @${handle} to this wallet instead`,
  noRoute: "Nothing routes to this X account yet. Set it up on Trade from X.",
  openPortfolio: "Open Portfolio",
  setUp: "Trade from X",
  card: {
    brand: "agari",
    claimed: "CLAIMED",
    settled: "TRADING BALANCE",
    waiting: "WAITING",
    eyebrow: "YOUR TRADING BALANCE",
    masked: "• •",
    sent: "yours",
    waitingWord: "waiting",
    paid: "in the wallet your account routes to",
    waitingFor: (handle: string) => `waiting for @${handle}`,
    reveal: "sign in with X to reveal",
    footer: "Only you can cash out.",
    network: "Solana devnet",
  },
  footnote: "Your calls sit in a vault that pays only the wallet that funded it. Not even us. Signing in with X just proves it’s the same you that placed them.",
} as const;
