/** The decision page's new words (S22); the section names and every sentence it showed before stay in `copy-record.ts`. */
export const DECISION = {
  sure: "sure",
  noModel: "no model",
  seq: (n: number) => `#${n}`,
  spend: "Spend",
  receive: "Receive",
  wouldBuy: (amount: string, name: string) => `${amount} of ${name}`,
  wouldSell: (amount: string, name: string) => `${amount} ${name}`,
  side: { buy: "Buy", sell: "Sell" } as const,
  strip: {
    aria: "The token price against its mark and its half-hour average",
    token: "Token",
    mark: "Mark",
    mean: "30-min average",
    index: "Pyth index",
    ceiling: (pct: string) => `Ceiling +${pct}`,
    above: "Above the ceiling",
    over: (price: string) => `over ${price}`,
  },
  chosen: "Chosen",
  turnedDown: "Turned down",
  checks: "Checks",
  passed: "Passed",
  refused: "Refused",
  flow: "Spend and receive",
  ledger: "Paper ledger",
  cash: "Cash",
  stepsAria: "The decision, section by section",
} as const;
